# cendre theme for fzf · medium
# https://github.com/Aejkatappaja/cendre
# generated by scripts/extras.lua, do not edit
#
# Source this file from your shell rc:
#   source /path/to/extras/fzf/cendre.sh

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --color=bg+:#26211f \
  --color=bg:#1d1917 \
  --color=border:#3d3633 \
  --color=fg:#a09384 \
  --color=fg+:#e6d5c2 \
  --color=gutter:#1d1917 \
  --color=header:#4e89a2 \
  --color=hl:#ea9875 \
  --color=hl+:#fcba81 \
  --color=info:#73665b \
  --color=marker:#43b16a \
  --color=pointer:#ea9875 \
  --color=prompt:#d1766e \
  --color=query:#e6d5c2 \
  --color=scrollbar:#3d3633 \
  --color=separator:#3d3633 \
  --color=spinner:#ea9875"
