" cendre · hard · https://github.com/Aejkatappaja/cendre
" generated by scripts/extras.lua, do not edit

set background=dark
hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "cendre"

if !has('gui_running') && &t_Co < 256
  finish
endif

" editor
hi Normal           guifg=#e6d5c2 guibg=#171311
hi NormalFloat      guifg=#e6d5c2 guibg=#0f0c0a
hi Cursor           guifg=#171311 guibg=#ea9875
hi CursorLine       guibg=#201b19 gui=NONE
hi CursorLineNr     guifg=#ea9875 gui=bold
hi LineNr           guifg=#4e4641
hi SignColumn       guifg=#4e4641 guibg=NONE
hi VertSplit        guifg=#362f2c guibg=NONE
hi StatusLine       guifg=#a09384 guibg=#2a2422
hi StatusLineNC     guifg=#4e4641 guibg=#201b19
hi TabLine          guifg=#73665b guibg=#201b19
hi TabLineFill      guibg=#201b19
hi TabLineSel       guifg=#e6d5c2 guibg=#171311 gui=bold
hi Pmenu            guifg=#e6d5c2 guibg=#201b19
hi PmenuSel         guifg=#171311 guibg=#ea9875 gui=bold
hi PmenuSbar        guibg=#2a2422
hi PmenuThumb       guibg=#463e3a
hi Visual           guibg=#2f1e17
hi Search           guifg=#171311 guibg=#fcba81
hi IncSearch        guifg=#171311 guibg=#ea9875
hi MatchParen       guifg=#ea9875 gui=bold
hi Folded           guifg=#73665b guibg=#201b19
hi NonText          guifg=#463e3a
hi SpecialKey       guifg=#463e3a
hi Directory        guifg=#4e89a2
hi Title            guifg=#ea9875 gui=bold
hi Conceal          guifg=#73665b
hi QuickFixLine     guibg=#2a2422 gui=bold
hi WildMenu         guifg=#171311 guibg=#ea9875
hi ColorColumn      guibg=#201b19

" messages
hi ModeMsg          guifg=#ea9875 gui=bold
hi MoreMsg          guifg=#58bdff
hi Question         guifg=#58bdff
hi ErrorMsg         guifg=#d25780 gui=bold
hi WarningMsg       guifg=#f4a21c

" syntax. one role, one pigment
hi Comment          guifg=#73665b gui=italic
hi Constant         guifg=#99af6b
hi String           guifg=#99af6b
hi Character        guifg=#99af6b
hi Number           guifg=#99af6b
hi Float            guifg=#99af6b
hi Boolean          guifg=#99af6b
hi Identifier       guifg=#e6d5c2 gui=NONE
hi Function         guifg=#fcba81
hi Statement        guifg=#d1766e gui=NONE
hi Conditional      guifg=#d1766e
hi Repeat           guifg=#d1766e
hi Label            guifg=#d1766e
hi Keyword          guifg=#d1766e
hi Exception        guifg=#d1766e
hi Operator         guifg=#a09384
hi PreProc          guifg=#d1766e
hi Include          guifg=#d1766e
hi Define           guifg=#d1766e
hi Macro            guifg=#ea9875
hi PreCondit        guifg=#d1766e
hi Type             guifg=#4e89a2 gui=NONE
hi StorageClass     guifg=#d1766e
hi Structure        guifg=#4e89a2
hi Typedef          guifg=#4e89a2
hi Special          guifg=#ea9875
hi SpecialChar      guifg=#ea9875
hi Tag              guifg=#d1766e
hi Delimiter        guifg=#a09384
hi SpecialComment   guifg=#73665b gui=italic
hi Debug            guifg=#d25780
hi Underlined       gui=underline
hi Ignore           guifg=#4e4641
hi Error            guifg=#d25780
hi Todo             guifg=#171311 guibg=#f4a21c gui=bold

" diff
hi DiffAdd          guibg=#202515
hi DiffDelete       guibg=#301d1b
hi DiffChange       guibg=#12262e
hi DiffText         guibg=#362f2c gui=bold

" spell
hi SpellBad     gui=undercurl guisp=#d25780
hi SpellCap     gui=undercurl guisp=#f4a21c
hi SpellLocal   gui=undercurl guisp=#58bdff
hi SpellRare    gui=undercurl guisp=#20c9cb
