" cendre · soft · https://github.com/Aejkatappaja/cendre
" generated by scripts/extras.lua, do not edit

set background=dark
hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "cendre-soft"

if !has('gui_running') && &t_Co < 256
  finish
endif

" editor
hi Normal           guifg=#e6d5c2 guibg=#231f1d
hi NormalFloat      guifg=#e6d5c2 guibg=#1a1716
hi Cursor           guifg=#231f1d guibg=#ea9875
hi CursorLine       guibg=#2d2725 gui=NONE
hi CursorLineNr     guifg=#ea9875 gui=bold
hi LineNr           guifg=#4e4641
hi SignColumn       guifg=#4e4641 guibg=NONE
hi VertSplit        guifg=#443c39 guibg=NONE
hi StatusLine       guifg=#a09384 guibg=#37312e
hi StatusLineNC     guifg=#4e4641 guibg=#2d2725
hi TabLine          guifg=#73665b guibg=#2d2725
hi TabLineFill      guibg=#2d2725
hi TabLineSel       guifg=#e6d5c2 guibg=#231f1d gui=bold
hi Pmenu            guifg=#e6d5c2 guibg=#2d2725
hi PmenuSel         guifg=#231f1d guibg=#ea9875 gui=bold
hi PmenuSbar        guibg=#37312e
hi PmenuThumb       guibg=#554c48
hi Visual           guibg=#3d2b23
hi Search           guifg=#231f1d guibg=#fcba81
hi IncSearch        guifg=#231f1d guibg=#ea9875
hi MatchParen       guifg=#ea9875 gui=bold
hi Folded           guifg=#73665b guibg=#2d2725
hi NonText          guifg=#554c48
hi SpecialKey       guifg=#554c48
hi Directory        guifg=#4e89a2
hi Title            guifg=#ea9875 gui=bold
hi Conceal          guifg=#73665b
hi QuickFixLine     guibg=#37312e gui=bold
hi WildMenu         guifg=#231f1d guibg=#ea9875
hi ColorColumn      guibg=#2d2725

" messages
hi ModeMsg          guifg=#ea9875 gui=bold
hi MoreMsg          guifg=#58bdff
hi Question         guifg=#58bdff
hi ErrorMsg         guifg=#d25780 gui=bold
hi WarningMsg       guifg=#f4a21c

" syntax. one role, one pigment
hi Comment          guifg=#73665b gui=italic
hi Constant         guifg=#99af6b
hi String           guifg=#99af6b
hi Character        guifg=#99af6b
hi Number           guifg=#99af6b
hi Float            guifg=#99af6b
hi Boolean          guifg=#99af6b
hi Identifier       guifg=#e6d5c2 gui=NONE
hi Function         guifg=#fcba81
hi Statement        guifg=#d1766e gui=NONE
hi Conditional      guifg=#d1766e
hi Repeat           guifg=#d1766e
hi Label            guifg=#d1766e
hi Keyword          guifg=#d1766e
hi Exception        guifg=#d1766e
hi Operator         guifg=#a09384
hi PreProc          guifg=#d1766e
hi Include          guifg=#d1766e
hi Define           guifg=#d1766e
hi Macro            guifg=#ea9875
hi PreCondit        guifg=#d1766e
hi Type             guifg=#4e89a2 gui=NONE
hi StorageClass     guifg=#d1766e
hi Structure        guifg=#4e89a2
hi Typedef          guifg=#4e89a2
hi Special          guifg=#ea9875
hi SpecialChar      guifg=#ea9875
hi Tag              guifg=#d1766e
hi Delimiter        guifg=#a09384
hi SpecialComment   guifg=#73665b gui=italic
hi Debug            guifg=#d25780
hi Underlined       gui=underline
hi Ignore           guifg=#4e4641
hi Error            guifg=#d25780
hi Todo             guifg=#231f1d guibg=#f4a21c gui=bold

" diff
hi DiffAdd          guibg=#2d3221
hi DiffDelete       guibg=#3e2a28
hi DiffChange       guibg=#1f333b
hi DiffText         guibg=#443c39 gui=bold

" spell
hi SpellBad     gui=undercurl guisp=#d25780
hi SpellCap     gui=undercurl guisp=#f4a21c
hi SpellLocal   gui=undercurl guisp=#58bdff
hi SpellRare    gui=undercurl guisp=#20c9cb
