local M = {}

-- One ordered surface registry: each tool consumes roles from palette.resolve.
-- A role may occur on several surfaces, but the resolved palette is the only
-- source of color values.
local ghostty = {
  { 'background', 'bg' },
  { 'foreground', 'fg' },
  { 'cursor-color', 'accent' },
  { 'cursor-text', 'bg' },
  { 'selection-background', 'selection' },
  { 'selection-foreground', 'fg' },
}

local opencode = {
  { 'primary', 'accent' },
  { 'secondary', 'type' },
  { 'accent', 'function' },
  { 'error', 'error' },
  { 'warning', 'warn' },
  { 'success', 'ok' },
  { 'info', 'info' },
  { 'text', 'fg' },
  { 'textMuted', 'dim' },
  { 'background', 'bg' },
  { 'backgroundPanel', 'deep' },
  { 'backgroundElement', 'raised' },
  { 'border', 'border' },
  { 'borderActive', 'accent' },
  { 'borderSubtle', 'border' },
  { 'diffAdded', 'ok' },
  { 'diffRemoved', 'error' },
  { 'diffContext', 'dim' },
  { 'diffHunkHeader', 'comment' },
  { 'diffHighlightAdded', 'ok' },
  { 'diffHighlightRemoved', 'error' },
  { 'diffAddedBg', 'add' },
  { 'diffRemovedBg', 'delete' },
  { 'diffContextBg', 'bg' },
  { 'diffLineNumber', 'gutter' },
  { 'diffAddedLineNumberBg', 'add' },
  { 'diffRemovedLineNumberBg', 'delete' },
  { 'markdownText', 'fg' },
  { 'markdownHeading', 'accent' },
  { 'markdownLink', 'type' },
  { 'markdownLinkText', 'type' },
  { 'markdownCode', 'literal' },
  { 'markdownBlockQuote', 'comment' },
  { 'markdownEmph', 'accent' },
  { 'markdownStrong', 'function' },
  { 'markdownHorizontalRule', 'border' },
  { 'markdownListItem', 'accent' },
  { 'markdownListEnumeration', 'accent' },
  { 'markdownImage', 'type' },
  { 'markdownImageText', 'type' },
  { 'markdownCodeBlock', 'literal' },
  { 'syntaxComment', 'comment' },
  { 'syntaxKeyword', 'keyword' },
  { 'syntaxFunction', 'function' },
  { 'syntaxVariable', 'fg' },
  { 'syntaxString', 'literal' },
  { 'syntaxNumber', 'literal' },
  { 'syntaxType', 'type' },
  { 'syntaxOperator', 'dim' },
  { 'syntaxPunctuation', 'dim' },
}

local bat_global = {
  { 'background', 'bg' },
  { 'foreground', 'fg' },
  { 'caret', 'accent' },
  { 'lineHighlight', 'line' },
  { 'selection', 'selection' },
  { 'gutterForeground', 'gutter' },
}

local bat_scopes = {
  { 'comment, punctuation.definition.comment', 'comment', 'italic' },
  { 'string, string.quoted, constant.numeric, constant.language', 'literal' },
  { 'constant.character.escape, string.regexp', 'literal' },
  { 'keyword, storage.type, storage.modifier, variable.language, entity.name.tag', 'keyword' },
  { 'keyword.operator, punctuation, meta.brace', 'dim' },
  { 'entity.name.function, support.function, meta.function-call', 'function' },
  { 'entity.name.type, entity.name.class, support.type, support.class, entity.name.namespace', 'type' },
  { 'variable, variable.other, constant.other', 'fg' },
  { 'variable.parameter, variable.other.member, entity.other.attribute-name, meta.decorator', 'accent' },
  { 'markup.heading, markup.list', 'accent' },
  { 'markup.bold', 'function', 'bold' },
  { 'markup.italic', 'fg', 'italic' },
  { 'markup.underline.link', 'type', 'underline' },
  { 'markup.raw', 'literal' },
  { 'markup.quote', 'comment', 'italic' },
  { 'markup.inserted', 'ok' },
  { 'markup.deleted', 'error' },
  { 'markup.changed', 'info' },
  { 'invalid', 'error' },
  { 'invalid.deprecated', 'warn' },
}

local function render_ghostty(colors)
  local lines = { '# Generated by scripts/extras.lua; do not edit.', '' }
  for _, entry in ipairs(ghostty) do
    lines[#lines + 1] = entry[1] .. ' = ' .. colors[entry[2]]
  end
  lines[#lines + 1] = ''
  for index = 0, 15 do
    lines[#lines + 1] = 'palette = ' .. index .. '=' .. colors['terminal' .. index]
  end
  return table.concat(lines, '\n') .. '\n'
end

local function render_opencode(colors)
  local lines = { '{', '  "$schema": "https://opencode.ai/theme.json",', '  "defs": {' }
  local roles = {}
  local seen = {}
  for _, entry in ipairs(opencode) do
    if not seen[entry[2]] then
      roles[#roles + 1] = entry[2]
      seen[entry[2]] = true
    end
  end
  for index, role in ipairs(roles) do
    lines[#lines + 1] = string.format('    "%s": "%s"%s', role, colors[role], index == #roles and '' or ',')
  end
  lines[#lines + 1] = '  },'
  lines[#lines + 1] = '  "theme": {'
  for index, entry in ipairs(opencode) do
    lines[#lines + 1] = string.format('    "%s": "%s"%s', entry[1], entry[2], index == #opencode and '' or ',')
  end
  lines[#lines + 1] = '  }'
  lines[#lines + 1] = '}'
  return table.concat(lines, '\n') .. '\n'
end

local function xml_setting(lines, key, value, indent)
  lines[#lines + 1] = indent .. '<key>' .. key .. '</key>'
  lines[#lines + 1] = indent .. '<string>' .. value .. '</string>'
end

local function render_bat(name, colors)
  local lines = {
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    '<dict>',
  }
  xml_setting(lines, 'name', name, '  ')
  lines[#lines + 1] = '  <key>settings</key>'
  lines[#lines + 1] = '  <array>'
  lines[#lines + 1] = '    <dict><key>settings</key><dict>'
  for _, entry in ipairs(bat_global) do
    xml_setting(lines, entry[1], colors[entry[2]], '      ')
  end
  lines[#lines + 1] = '    </dict></dict>'
  for _, entry in ipairs(bat_scopes) do
    lines[#lines + 1] = '    <dict>'
    xml_setting(lines, 'scope', entry[1], '      ')
    lines[#lines + 1] = '      <key>settings</key><dict>'
    xml_setting(lines, 'foreground', colors[entry[2]], '        ')
    if entry[3] then xml_setting(lines, 'fontStyle', entry[3], '        ') end
    lines[#lines + 1] = '      </dict>'
    lines[#lines + 1] = '    </dict>'
  end
  lines[#lines + 1] = '  </array>'
  lines[#lines + 1] = '</dict>'
  lines[#lines + 1] = '</plist>'
  return table.concat(lines, '\n') .. '\n'
end

function M.render()
  local files = {}
  for _, temperature in ipairs({ 'balanced', 'warm', 'cool' }) do
    for _, depth in ipairs({ 'hard', 'medium', 'soft' }) do
      local name = require('grisaille.names').for_axes(temperature, depth)
      local colors = require('grisaille.palette').resolve(temperature, depth)
      files['extras/bat/' .. name .. '.tmTheme'] = render_bat(name, colors)
      files['extras/ghostty/' .. name] = render_ghostty(colors)
      files['extras/opencode/' .. name .. '.json'] = render_opencode(colors)
    end
  end
  return files
end

return M
