local M = {}

-- Other editors. The role map is the one the Neovim groups use, so a keyword is
-- cinder here for the same reason it is cinder there.

local palette = require("cendre.palette")

--- @param bg string
--- @return string
function M.vim(bg)
  local c = palette.get(bg)

  --- @param group string
  --- @param fg string|nil
  --- @param bgc string|nil
  --- @param gui string|nil
  --- @return string
  local function hi(group, fg, bgc, gui)
    local parts = { ("hi %-16s"):format(group) }
    if fg then table.insert(parts, "guifg=" .. fg) end
    if bgc then table.insert(parts, "guibg=" .. bgc) end
    if gui then table.insert(parts, "gui=" .. gui) end
    return table.concat(parts, " ")
  end

  local lines = {
    '" cendre · ' .. bg .. " · https://github.com/Aejkatappaja/cendre",
    '" generated by scripts/extras.lua, do not edit',
    "",
    "set background=dark",
    "hi clear",
    'if exists("syntax_on")',
    "  syntax reset",
    "endif",
    ('let g:colors_name = "%s"'):format(palette.name(bg)),
    "",
    "if !has('gui_running') && &t_Co < 256",
    "  finish",
    "endif",
    "",
    '" editor',
    hi("Normal", c.fg, c.bg0),
    hi("NormalFloat", c.fg, c.bg_deep),
    hi("Cursor", c.bg0, c.ember),
    hi("CursorLine", nil, c.bg1, "NONE"),
    hi("CursorLineNr", c.ember, nil, "bold"),
    hi("LineNr", c.gutter),
    hi("SignColumn", c.gutter, "NONE"),
    hi("VertSplit", c.bg3, "NONE"),
    hi("StatusLine", c.fg_dim, c.bg2),
    hi("StatusLineNC", c.gutter, c.bg1),
    hi("TabLine", c.comment, c.bg1),
    hi("TabLineFill", nil, c.bg1),
    hi("TabLineSel", c.fg, c.bg0, "bold"),
    hi("Pmenu", c.fg, c.bg1),
    hi("PmenuSel", c.bg0, c.ember, "bold"),
    hi("PmenuSbar", nil, c.bg2),
    hi("PmenuThumb", nil, c.bg4),
    hi("Visual", nil, c.vis),
    hi("Search", c.bg0, c.brass),
    hi("IncSearch", c.bg0, c.ember),
    hi("MatchParen", c.ember, nil, "bold"),
    hi("Folded", c.comment, c.bg1),
    hi("NonText", c.bg4),
    hi("SpecialKey", c.bg4),
    hi("Directory", c.frost),
    hi("Title", c.ember, nil, "bold"),
    hi("Conceal", c.comment),
    hi("QuickFixLine", nil, c.bg2, "bold"),
    hi("WildMenu", c.bg0, c.ember),
    hi("ColorColumn", nil, c.bg1),
    "",
    '" messages',
    hi("ModeMsg", c.ember, nil, "bold"),
    hi("MoreMsg", c.info),
    hi("Question", c.info),
    hi("ErrorMsg", c.error, nil, "bold"),
    hi("WarningMsg", c.warn),
    "",
    '" syntax. one role, one pigment',
    hi("Comment", c.comment, nil, "italic"),
    hi("Constant", c.sap),
    hi("String", c.sap),
    hi("Character", c.sap),
    hi("Number", c.sap),
    hi("Float", c.sap),
    hi("Boolean", c.sap),
    hi("Identifier", c.fg, nil, "NONE"),
    hi("Function", c.brass),
    hi("Statement", c.cinder, nil, "NONE"),
    hi("Conditional", c.cinder),
    hi("Repeat", c.cinder),
    hi("Label", c.cinder),
    hi("Keyword", c.cinder),
    hi("Exception", c.cinder),
    hi("Operator", c.fg_dim),
    hi("PreProc", c.cinder),
    hi("Include", c.cinder),
    hi("Define", c.cinder),
    hi("Macro", c.ember),
    hi("PreCondit", c.cinder),
    hi("Type", c.frost, nil, "NONE"),
    hi("StorageClass", c.cinder),
    hi("Structure", c.frost),
    hi("Typedef", c.frost),
    hi("Special", c.ember),
    hi("SpecialChar", c.ember),
    hi("Tag", c.cinder),
    hi("Delimiter", c.fg_dim),
    hi("SpecialComment", c.comment, nil, "italic"),
    hi("Debug", c.error),
    hi("Underlined", nil, nil, "underline"),
    hi("Ignore", c.gutter),
    hi("Error", c.error),
    hi("Todo", c.bg0, c.warn, "bold"),
    "",
    '" diff',
    hi("DiffAdd", nil, c.add),
    hi("DiffDelete", nil, c.del),
    hi("DiffChange", nil, c.mod),
    hi("DiffText", nil, c.bg3, "bold"),
    "",
    '" spell',
    "hi SpellBad     gui=undercurl guisp=" .. c.error,
    "hi SpellCap     gui=undercurl guisp=" .. c.warn,
    "hi SpellLocal   gui=undercurl guisp=" .. c.info,
    "hi SpellRare    gui=undercurl guisp=" .. c.hint,
  }
  return table.concat(lines, "\n") .. "\n"
end

--- @param bg string
--- @return string
function M.helix(bg)
  local c = palette.get(bg)
  return ([[
# cendre · %s · https://github.com/Aejkatappaja/cendre
# generated by scripts/extras.lua, do not edit
#
# Install: copy to ~/.config/helix/themes/cendre.toml, then set
# `theme = "%s"` in ~/.config/helix/config.toml.

# syntax. Helix falls back on the longest prefix it has a rule for, so a scope is
# only named here when inheriting would hand it the wrong pigment.
"keyword" = "cinder"
"keyword.control" = "cinder"
"keyword.directive" = "cinder"
"keyword.storage" = "cinder"
"operator" = "fg_dim"
"function" = "brass"
"function.builtin" = "brass"
"function.method" = "brass"
"function.macro" = "ember"
"constructor" = "frost"
"type" = "frost"
"type.builtin" = "frost"
"type.enum.variant" = "sap"
"constant" = "fg"
"constant.builtin" = "sap"
"constant.numeric" = "sap"
"constant.character" = "sap"
"constant.character.escape" = "ember"
"string" = "sap"
"string.regexp" = "ember"
"string.special" = "ember"
# a path or a url points somewhere, which is the frost job, so the two step out
# of the ember family the rest of string.special sits in
"string.special.path" = "frost"
"string.special.url" = { fg = "frost", modifiers = ["underlined"] }
"comment" = { fg = "comment", modifiers = ["italic"] }
"variable" = "fg"
"variable.builtin" = "cinder"
"variable.parameter" = "ember"
"variable.other.member" = "ember"
"label" = "cinder"
"namespace" = "frost"
"attribute" = "ember"
"punctuation" = "fg_dim"
"punctuation.delimiter" = "fg_dim"
"punctuation.bracket" = "fg_dim"
# interpolation braces and format specifiers carry meaning a comma does not
"punctuation.special" = "ember"
"special" = "ember"
"tag" = "cinder"
"tabstop" = { bg = "bg2" }

# markup. Six heading levels out of five pigments, so the last one steps down to
# fg_dim rather than repeating a pigment.
"markup.heading" = { fg = "ember", modifiers = ["bold"] }
"markup.heading.1" = { fg = "ember", modifiers = ["bold"] }
"markup.heading.2" = { fg = "brass", modifiers = ["bold"] }
"markup.heading.3" = { fg = "frost", modifiers = ["bold"] }
"markup.heading.4" = { fg = "sap", modifiers = ["bold"] }
"markup.heading.5" = { fg = "cinder", modifiers = ["bold"] }
"markup.heading.6" = { fg = "fg_dim", modifiers = ["bold"] }
"markup.list" = "ember"
"markup.list.checked" = "ok"
"markup.list.unchecked" = "comment"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link" = "frost"
"markup.link.url" = { fg = "comment", modifiers = ["underlined"] }
"markup.link.text" = "frost"
"markup.quote" = { fg = "comment", modifiers = ["italic"] }
"markup.raw" = "sap"

# ui
"ui.background" = { bg = "bg0" }
"ui.background.separator" = "bg3"
"ui.text" = "fg"
"ui.text.focus" = { fg = "fg", modifiers = ["bold"] }
"ui.text.inactive" = "comment"
"ui.text.info" = "fg_dim"
"ui.text.directory" = "frost"
# the cursor answers to the mode, on the same three pigments the statusline uses,
# so the block under your hand and the badge in the corner never disagree
"ui.cursor" = { fg = "bg0", bg = "ember" }
"ui.cursor.normal" = { fg = "bg0", bg = "ember" }
"ui.cursor.insert" = { fg = "bg0", bg = "ok" }
"ui.cursor.select" = { fg = "bg0", bg = "info" }
"ui.cursor.primary" = { fg = "bg0", bg = "ember" }
"ui.cursor.primary.normal" = { fg = "bg0", bg = "ember" }
"ui.cursor.primary.insert" = { fg = "bg0", bg = "ok" }
"ui.cursor.primary.select" = { fg = "bg0", bg = "info" }
"ui.cursor.match" = { fg = "ember", modifiers = ["bold"] }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg1" }
"ui.cursorcolumn.primary" = { bg = "bg1" }
"ui.cursorcolumn.secondary" = { bg = "bg1" }
# the warm tint marks the selection you are driving. The rest take plain ground,
# one step darker, because with thirty cursors down a file every one of them
# cannot be the one, and hue alone does not carry that at this chroma.
"ui.selection" = { bg = "bg1" }
"ui.selection.primary" = { bg = "vis" }
"ui.linenr" = "gutter"
"ui.linenr.selected" = { fg = "ember", modifiers = ["bold"] }
# the gutter takes the cursorline too, or the band stops where the text starts
"ui.gutter" = { bg = "bg0" }
"ui.gutter.selected" = { bg = "bg1" }
"ui.statusline" = { fg = "fg_dim", bg = "bg2" }
"ui.statusline.inactive" = { fg = "gutter", bg = "bg1" }
"ui.statusline.normal" = { fg = "bg0", bg = "ember", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg0", bg = "ok", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg0", bg = "info", modifiers = ["bold"] }
"ui.statusline.separator" = { fg = "bg3", bg = "bg2" }
"ui.bufferline" = { fg = "comment", bg = "bg1" }
"ui.bufferline.active" = { fg = "fg", bg = "bg0", modifiers = ["bold"] }
"ui.bufferline.background" = { bg = "bg1" }
"ui.popup" = { fg = "fg", bg = "bg_deep" }
"ui.window" = { fg = "bg3" }
"ui.help" = { fg = "fg", bg = "bg_deep" }
"ui.menu" = { fg = "fg", bg = "bg1" }
"ui.menu.selected" = { fg = "bg0", bg = "ember", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "bg4", bg = "bg2" }
"ui.picker.header" = "comment"
"ui.picker.header.column.active" = { fg = "ember", modifiers = ["bold"] }
"ui.virtual.whitespace" = "bg3"
"ui.virtual.ruler" = { bg = "bg1" }
"ui.virtual.indent-guide" = "bg2"
"ui.virtual.wrap" = "bg3"
"ui.virtual.inlay-hint" = { fg = "gutter", modifiers = ["italic"] }
# a jump label is read in the time it takes to type it, so it gets the loudest
# pair the theme has rather than a pigment on the ground
"ui.virtual.jump-label" = { fg = "bg0", bg = "ember", modifiers = ["bold"] }
"ui.highlight" = { bg = "bg2" }
"ui.highlight.frameline" = { bg = "bg2" }
"ui.debug.breakpoint" = "error"
"ui.debug.active" = "warn"

# diagnostics, their own family
"error" = "error"
"warning" = "warn"
"info" = "info"
"hint" = "hint"
"diagnostic.error" = { underline = { color = "error", style = "curl" } }
"diagnostic.warning" = { underline = { color = "warn", style = "curl" } }
"diagnostic.info" = { underline = { color = "info", style = "curl" } }
"diagnostic.hint" = { underline = { color = "hint", style = "curl" } }
# dead and dying code says what it is by receding, so neither takes a curl
"diagnostic.unnecessary" = { fg = "gutter" }
"diagnostic.deprecated" = { fg = "comment", modifiers = ["crossed_out"] }

# diff
"diff.plus" = "ok"
"diff.plus.gutter" = "ok"
"diff.minus" = "error"
"diff.minus.gutter" = "error"
"diff.delta" = "info"
"diff.delta.gutter" = "info"
"diff.delta.conflict" = "warn"

[palette]
bg_deep = "%s"
bg0 = "%s"
bg1 = "%s"
bg2 = "%s"
bg3 = "%s"
bg4 = "%s"
bg5 = "%s"
fg = "%s"
fg_dim = "%s"
comment = "%s"
gutter = "%s"
vis = "%s"
cinder = "%s"
ember = "%s"
brass = "%s"
sap = "%s"
frost = "%s"
error = "%s"
warn = "%s"
ok = "%s"
hint = "%s"
info = "%s"
]]):format(bg, palette.name(bg),
    c.bg_deep, c.bg0, c.bg1, c.bg2, c.bg3, c.bg4, c.bg5,
    c.fg, c.fg_dim, c.comment, c.gutter, c.vis,
    c.cinder, c.ember, c.brass, c.sap, c.frost,
    c.error, c.warn, c.ok, c.hint, c.info)
end

--- @param bg string
--- @return string
--- The licence, copied beside the Zed manifest. Their packaging step reads it from
--- the extension directory rather than from the repository root, which with a path
--- field means extras/zed and not here, so the copy is required and it is read from
--- the root file rather than retyped, which is what stops the two from diverging.
--- @return string
function M.zed_licence()
  local fd = assert(io.open("LICENSE", "r"), "LICENSE is missing from the repository root")
  local body = fd:read("*a")
  fd:close()
  return body
end

--- The Zed extension manifest. One for the three themes, since Zed lists an
--- extension once and its themes inside it.
---
--- The version is a literal on purpose. It could be read from
--- .release-please-manifest.json, but then a release pull request would bump the
--- manifest, the drift check would re-render this file at the new number, compare
--- it to the committed one at the old number, and fail. Zed versions extensions
--- independently anyway: bump this line when submitting a store update.
--- @return string
function M.zed_extension()
  return ([[
id = "cendre-theme"
name = "cendre"
version = "0.1.0"
schema_version = 1
authors = ["Aejkatappaja"]
description = "%s"
repository = "https://github.com/Aejkatappaja/cendre"
]]):format("Dark colorscheme with every hue computed from a wood fire's emission spectrum.")
end

function M.zed(bg)
  local c = palette.get(bg)
  local name = palette.name(bg)

  --- @param scope string
  --- @param hex string
  --- @param style string|nil
  --- @param weight integer|nil
  --- @return string
  local function syn(scope, hex, style, weight)
    return ('        "%s": { "color": "%sff", "font_style": %s, "font_weight": %s }')
      :format(scope, hex, style and ('"' .. style .. '"') or "null", weight or "null")
  end

  -- Every capture takes the colour its Neovim counterpart takes, so the two
  -- editors cannot disagree about what a parameter or a field looks like.
  local syntax = {
    syn("comment", c.comment, "italic"),
    syn("comment.doc", c.comment, "italic"),
    syn("keyword", c.cinder),
    syn("operator", c.fg_dim),
    syn("punctuation", c.fg_dim),
    syn("punctuation.bracket", c.fg_dim),
    syn("punctuation.delimiter", c.fg_dim),
    syn("punctuation.special", c.ember),
    syn("function", c.brass),
    syn("function.method", c.brass),
    syn("function.builtin", c.brass),
    syn("constructor", c.frost),
    syn("type", c.frost),
    syn("type.builtin", c.frost),
    syn("string", c.sap),
    syn("string.special", c.ember),
    syn("string.escape", c.ember),
    syn("string.regex", c.ember),
    syn("number", c.sap),
    syn("boolean", c.sap),
    syn("constant", c.fg),
    syn("constant.builtin", c.sap),
    syn("variable", c.fg),
    syn("variable.special", c.cinder),
    syn("property", c.ember),
    syn("attribute", c.ember),
    syn("label", c.cinder),
    syn("lifetime", c.cinder),
    syn("tag", c.cinder),
    syn("selector", c.cinder),
    syn("emphasis", c.fg, "italic"),
    syn("emphasis.strong", c.fg, nil, 700),
    syn("link_text", c.frost),
    syn("link_uri", c.comment),
    syn("title", c.ember, nil, 700),
    syn("markup.heading", c.ember, nil, 700),
    syn("markup.link.url", c.comment),
    syn("primary", c.fg),
    syn("predictive", c.gutter),
    syn("hint", c.gutter),
    syn("variable.parameter", c.ember),
    syn("variable.member", c.ember),
    syn("variable.other.member", c.ember),
    syn("variable.builtin", c.cinder),
    syn("enum", c.frost),
    syn("variant", c.frost),
    syn("namespace", c.frost),
    syn("module", c.frost),
    syn("concept", c.frost),
    syn("preproc", c.cinder),
    syn("embedded", c.fg),
    syn("string.doc", c.sap),
    syn("string.special.symbol", c.ember),
    syn("text.literal", c.sap),
    syn("tag.attribute", c.ember),
    syn("tag.delimiter", c.fg_dim),
    syn("punctuation.list_marker", c.ember),
    syn("diff.plus", c.ok),
    syn("diff.minus", c.error),
    syn("diff.delta", c.info),
  }

  -- Ordered pairs rather than one positional format string. At 140 keys a
  -- template means an inserted line silently shifts every colour after it onto
  -- its neighbour's key, and nothing short of reading the output would catch it.
  local style = {
    { "background.appearance", "opaque" },
    { "accents", { c.cinder, c.ember, c.brass, c.sap, c.frost } },
    { "background", c.bg0 },
    { "editor.background", c.bg0 },
    { "editor.foreground", c.fg },
    { "editor.gutter.background", c.bg0 },
    { "editor.line_number", c.gutter },
    { "editor.active_line_number", c.ember },
    { "editor.active_line.background", c.bg1 },
    { "editor.highlighted_line.background", c.bg2 },
    { "editor.wrap_guide", c.bg3 },
    { "editor.active_wrap_guide", c.bg4 },
    { "editor.document_highlight.read_background", c.bg2 },
    { "editor.document_highlight.write_background", c.bg2 },
    { "editor.document_highlight.bracket_background", c.bg2 },
    { "editor.invisible", c.bg4 },
    { "editor.indent_guide", c.bg2 },
    { "editor.indent_guide_active", c.bg4 },
    { "editor.subheader.background", c.bg1 },
    { "elevated_surface.background", c.bg_deep },
    { "surface.background", c.bg1 },
    { "text", c.fg },
    { "text.muted", c.fg_dim },
    { "text.placeholder", c.gutter },
    { "text.disabled", c.gutter },
    { "text.accent", c.ember },
    { "link_text.hover", c.ember },
    { "icon", c.fg },
    { "icon.accent", c.ember },
    { "icon.muted", c.fg_dim },
    { "icon.disabled", c.gutter },
    { "icon.placeholder", c.gutter },
    { "border", c.bg5 },
    { "border.variant", c.bg2 },
    { "border.focused", c.ember },
    { "border.selected", c.ember },
    { "border.transparent", c.bg0 },
    { "pane.focused_border", c.ember },
    { "pane_group.border", c.bg3 },
    { "border.disabled", c.bg2 },
    { "element.background", c.bg1 },
    { "element.hover", c.bg2 },
    { "element.active", c.bg3 },
    { "element.selected", c.bg2 },
    { "search.match_background", c.brass .. "66" },
    { "element.disabled", c.bg1 },
    { "ghost_element.background", "#00000000" },
    { "ghost_element.hover", c.bg2 },
    { "ghost_element.active", c.bg3 },
    { "ghost_element.selected", c.bg2 },
    { "ghost_element.disabled", c.bg1 },
    { "drop_target.background", c.vis },
    { "title_bar.background", c.bg_deep },
    { "title_bar.inactive_background", c.bg_deep },
    { "status_bar.background", c.bg2 },
    { "toolbar.background", c.bg0 },
    { "tab_bar.background", c.bg1 },
    { "tab.active_background", c.bg0 },
    { "tab.inactive_background", c.bg1 },
    { "panel.background", c.bg_deep },
    { "panel.focused_border", c.ember },
    { "panel.indent_guide", c.bg2 },
    { "panel.indent_guide_active", c.bg4 },
    { "panel.indent_guide_hover", c.bg3 },
    { "scrollbar.thumb.background", c.bg4 },
    { "scrollbar.thumb.hover_background", c.bg5 },
    { "scrollbar.thumb.border", c.bg3 },
    { "scrollbar.track.background", c.bg0 },
    { "scrollbar.track.border", c.bg3 },
    { "terminal.background", c.bg0 },
    { "terminal.foreground", c.fg },
    { "terminal.bright_foreground", c.fg },
    { "terminal.dim_foreground", c.fg_dim },
    { "terminal.ansi.black", c.terminal_black },
    { "terminal.ansi.red", c.terminal_red },
    { "terminal.ansi.green", c.terminal_green },
    { "terminal.ansi.yellow", c.terminal_yellow },
    { "terminal.ansi.blue", c.terminal_blue },
    { "terminal.ansi.magenta", c.terminal_magenta },
    { "terminal.ansi.cyan", c.terminal_cyan },
    { "terminal.ansi.white", c.terminal_white },
    { "terminal.ansi.bright_black", c.terminal_bright_black },
    { "terminal.ansi.bright_red", c.terminal_bright_red },
    { "terminal.ansi.bright_green", c.terminal_bright_green },
    { "terminal.ansi.bright_yellow", c.terminal_bright_yellow },
    { "terminal.ansi.bright_blue", c.terminal_bright_blue },
    { "terminal.ansi.bright_magenta", c.terminal_bright_magenta },
    { "terminal.ansi.bright_cyan", c.terminal_bright_cyan },
    { "terminal.ansi.bright_white", c.terminal_bright_white },
    { "terminal.ansi.background", c.bg0 },
    { "terminal.ansi.dim_black", c.terminal_black },
    { "terminal.ansi.dim_red", c.terminal_red },
    { "terminal.ansi.dim_green", c.terminal_green },
    { "terminal.ansi.dim_yellow", c.terminal_yellow },
    { "terminal.ansi.dim_blue", c.terminal_blue },
    { "terminal.ansi.dim_magenta", c.terminal_magenta },
    { "terminal.ansi.dim_cyan", c.terminal_cyan },
    { "terminal.ansi.dim_white", c.terminal_white },
    { "error", c.error },
    { "error.background", c.del },
    { "error.border", c.error },
    { "warning", c.warn },
    { "warning.background", c.bg1 },
    { "warning.border", c.warn },
    { "info", c.info },
    { "info.background", c.mod },
    { "info.border", c.info },
    { "hint", c.hint },
    { "hint.background", c.bg1 },
    { "hint.border", c.hint },
    { "success", c.ok },
    { "success.background", c.add },
    { "success.border", c.ok },
    { "created", c.ok },
    { "created.background", c.add },
    { "created.border", c.ok },
    { "modified", c.info },
    { "modified.background", c.mod },
    { "modified.border", c.info },
    { "deleted", c.error },
    { "deleted.background", c.del },
    { "deleted.border", c.error },
    { "conflict", c.warn },
    { "conflict.background", c.bg1 },
    { "conflict.border", c.warn },
    { "ignored", c.gutter },
    { "ignored.background", c.bg1 },
    { "ignored.border", c.gutter },
    { "renamed", c.info },
    { "renamed.background", c.mod },
    { "renamed.border", c.info },
    { "predictive", c.gutter },
    { "predictive.background", c.bg1 },
    { "predictive.border", c.gutter },
    { "hidden", c.gutter },
    { "hidden.background", c.bg1 },
    { "hidden.border", c.gutter },
    { "unreachable", c.gutter },
    { "unreachable.background", c.bg1 },
    { "unreachable.border", c.gutter },
  }

  --- @param v string|string[] a six digit hex, a list of them, or a literal
  --- @return string the JSON value
  local function value(v)
    if type(v) == "table" then
      local out = {}
      for i, hex in ipairs(v) do out[i] = ('"%sff"'):format(hex) end
      return "[" .. table.concat(out, ", ") .. "]"
    end
    -- eight digits already carry their alpha, and the enums are not colours
    if v:match("^#%x%x%x%x%x%x$") then return ('"%sff"'):format(v) end
    return ('"%s"'):format(v)
  end

  local rows = {}
  for _, entry in ipairs(style) do
    rows[#rows + 1] = ('        "%s": %s,'):format(entry[1], value(entry[2]))
  end

  return ([[
{
  "$schema": "https://zed.dev/schema/themes/v0.2.0.json",
  "name": "%s",
  "author": "Aejkatappaja",
  "themes": [
    {
      "name": "%s",
      "appearance": "dark",
      "style": {
%s
        "players": [
          { "cursor": "%sff", "background": "%sff", "selection": "%sff" }
        ],
        "syntax": {
%s
        }
      }
    }
  ]
}
]]):format(name, name, table.concat(rows, "\n"), c.ember, c.ember, c.vis,
    table.concat(syntax, ",\n"))
end

-- The Yaak plugin. Yaak installs a package instead of reading this repository,
-- so extras/yaak is what `yaakcli build` publishes: one theme per depth, in the
-- file that carries its name, and src/index.ts lists the three.

local YAAK_THEME = [==[
import type { Theme } from '@yaakapp/api';

export const @ident@: Theme = {
  id: '@id@',
  label: '@label@',
  dark: true,
  base: {
    surface: '@bg0@',
    surfaceHighlight: '@bg1@',
    surfaceActive: '@bg2@',
    selection: '@vis@',
    text: '@fg@',
    textSubtle: '@fg_dim@',
    textSubtlest: '@comment@',
    border: '@bg3@',
    borderSubtle: '@bg2@',
    borderFocus: '@ember@',
    primary: '@ember@',
    secondary: '@frost@',
    info: '@info@',
    success: '@ok@',
    notice: '@brass@',
    warning: '@warn@',
    danger: '@error@',
  },
  components: {
    appHeader: { surface: '@bg2@', border: '@bg3@' },
    sidebar: { surface: '@bg_deep@', border: '@bg2@' },
    responsePane: { surface: '@bg0@', border: '@bg3@' },
    editor: { surface: '@bg0@' },
    dialog: { surface: '@bg_deep@', border: '@bg3@' },
    menu: { surface: '@bg_deep@', border: '@bg3@' },
    toast: { surface: '@bg_deep@', border: '@bg3@' },
    input: { surface: '@bg1@', border: '@bg3@' },
    urlBar: { surface: '@bg1@', border: '@bg3@' },
    button: {
      primary: '@ember@',
      secondary: '@frost@',
      info: '@info@',
      success: '@ok@',
      notice: '@brass@',
      warning: '@warn@',
      danger: '@error@',
    },
  },
};
]==]

--- The exported binding for a depth: cendre, cendreMedium, cendreSoft.
--- @param name string
--- @return string
local function yaak_ident(name)
  return (name:gsub("%-(%l)", function(l) return l:upper() end))
end

--- The label a depth wears in Yaak's theme selector.
--- @param name string
--- @return string
local function yaak_label(name)
  return (name:gsub("^%l", string.upper):gsub("%-(%l)", function(l) return " " .. l:upper() end))
end

--- One theme module. Roles are the Neovim ones: ember is the accent, frost is a
--- type, and brass takes `notice` so a notice and a warning are not two shades of
--- the same amber. `shadow` and `backdrop` are left out because both want alpha.
--- @param bg string
--- @return string
function M.yaak(bg)
  local c = palette.get(bg)
  local name = palette.name(bg)

  local vars = {
    bg0 = c.bg0,
    bg1 = c.bg1,
    bg2 = c.bg2,
    bg3 = c.bg3,
    bg_deep = c.bg_deep,
    brass = c.brass,
    comment = c.comment,
    ember = c.ember,
    error = c.error,
    fg = c.fg,
    fg_dim = c.fg_dim,
    frost = c.frost,
    id = name,
    ident = yaak_ident(name),
    info = c.info,
    label = yaak_label(name),
    ok = c.ok,
    vis = c.vis,
    warn = c.warn,
  }

  return (YAAK_THEME:gsub("@([%w_]+)@", vars))
end

--- The plugin entry point. Yaak's themes field is a list, so one install carries
--- the three depths and the reader picks one in the selector.
--- @return string
function M.yaak_index()
  local imports, idents = {}, {}
  for _, bg in ipairs(palette.backgrounds) do
    local name = palette.name(bg)
    local ident = yaak_ident(name)
    table.insert(imports, ("import { %s } from './%s';"):format(ident, name))
    table.insert(idents, ident)
  end

  return ([[
import type { PluginDefinition } from '@yaakapp/api';
%s

export const plugin: PluginDefinition = {
  themes: [%s],
};
]]):format(table.concat(imports, "\n"), table.concat(idents, ", "))
end

--- The package manifest. The version is a literal for the same reason the Zed
--- one is: read from the release manifest, a release would re-render this file at
--- a new number and fail the drift check.
--- @return string
function M.yaak_package()
  return ([[
{
  "name": "@aejkatappaja/cendre-theme",
  "displayName": "Cendre for Yaak",
  "description": "%s",
  "version": "0.1.0",
  "private": false,
  "license": "MIT",
  "author": "Aejkatappaja",
  "repository": {
    "type": "git",
    "url": "https://github.com/Aejkatappaja/cendre.git"
  },
  "keywords": ["yaak", "yaak-plugin", "theme", "dark", "cendre"],
  "scripts": {
    "build": "yaakcli build"
  },
  "dependencies": {
    "@yaakapp/api": "^0.8.3"
  },
  "devDependencies": {
    "@yaakapp/cli": "^2026.6.1",
    "typescript": "^5.5.2"
  }
}
]]):format("Dark colorscheme with every hue computed from a wood fire's emission spectrum. Three depths.")
end

--- @return string
function M.yaak_tsconfig()
  return [[
{
  "compilerOptions": {
    "target": "es2021",
    "module": "ESNext",
    "moduleResolution": "Node",
    "lib": ["ESNext"],
    "strict": true,
    "noEmit": true,
    "skipLibCheck": true,
    "isolatedModules": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src"]
}
]]
end

return M
