local M = {}

-- Terminals and multiplexers. Each one takes the same sixteen ANSI slots the
-- palette already derives, so none of these files decides a colour: they only
-- decide a syntax.

local palette = require("cendre.palette")

local HEADER = "# cendre · %s · https://github.com/Aejkatappaja/cendre"
local GENERATED = "# generated by scripts/extras.lua, do not edit"

--- The sixteen ANSI slots in order, so every terminal writer indexes the same list.
--- @param c table resolved palette
--- @return string[]
local function ansi(c)
  return {
    c.terminal_black, c.terminal_red, c.terminal_green, c.terminal_yellow,
    c.terminal_blue, c.terminal_magenta, c.terminal_cyan, c.terminal_white,
    c.terminal_bright_black, c.terminal_bright_red, c.terminal_bright_green,
    c.terminal_bright_yellow, c.terminal_bright_blue, c.terminal_bright_magenta,
    c.terminal_bright_cyan, c.terminal_bright_white,
  }
end

--- @param bg string depth name
--- @return string
function M.ghostty(bg)
  local c = palette.get(bg)
  local out = {
    HEADER:format(bg), GENERATED, "",
    "background = " .. c.bg0,
    "foreground = " .. c.fg,
    "cursor-color = " .. c.ember,
    "cursor-text = " .. c.bg0,
    "selection-background = " .. c.vis,
    "selection-foreground = " .. c.fg,
    "",
  }
  for i, hex in ipairs(ansi(c)) do
    table.insert(out, ("palette = %d=%s"):format(i - 1, hex))
  end
  return table.concat(out, "\n") .. "\n"
end

--- @param bg string
--- @return string
function M.kitty(bg)
  local c = palette.get(bg)
  local slots = ansi(c)
  local out = {
    HEADER:format(bg), GENERATED,
    "# then in kitty.conf:  include cendre.conf", "",
    "background " .. c.bg0,
    "foreground " .. c.fg,
    "cursor " .. c.ember,
    "cursor_text_color " .. c.bg0,
    "selection_background " .. c.vis,
    "selection_foreground " .. c.fg,
    "url_color " .. c.frost,
    "active_border_color " .. c.ember,
    "inactive_border_color " .. c.bg3,
    "bell_border_color " .. c.warn,
    "active_tab_background " .. c.bg0,
    "active_tab_foreground " .. c.fg,
    "inactive_tab_background " .. c.bg_deep,
    "inactive_tab_foreground " .. c.comment,
    "",
  }
  for i, hex in ipairs(slots) do
    if i == 1 then table.insert(out, "# normal") end
    if i == 9 then table.insert(out, "\n# bright") end
    table.insert(out, ("color%d %s"):format(i - 1, hex))
  end
  return table.concat(out, "\n") .. "\n"
end

--- @param bg string
--- @return string
function M.alacritty(bg)
  local c = palette.get(bg)
  local s = ansi(c)
  return ([[
%s
%s
# then in alacritty.toml:  import = ["~/.config/alacritty/cendre.toml"]

[colors.primary]
background = "%s"
foreground = "%s"

[colors.cursor]
cursor = "%s"
text = "%s"

[colors.vi_mode_cursor]
cursor = "%s"
text = "%s"

[colors.selection]
background = "%s"
text = "%s"

[colors.search.matches]
background = "%s"
foreground = "%s"

[colors.search.focused_match]
background = "%s"
foreground = "%s"

[colors.hints.start]
background = "%s"
foreground = "%s"

[colors.hints.end]
background = "%s"
foreground = "%s"

[colors.normal]
black = "%s"
red = "%s"
green = "%s"
yellow = "%s"
blue = "%s"
magenta = "%s"
cyan = "%s"
white = "%s"

[colors.bright]
black = "%s"
red = "%s"
green = "%s"
yellow = "%s"
blue = "%s"
magenta = "%s"
cyan = "%s"
white = "%s"
]]):format(
    HEADER:format(bg), GENERATED,
    c.bg0, c.fg,
    c.ember, c.bg0,
    c.frost, c.bg0,
    c.vis, c.fg,
    c.bg3, c.fg,
    c.brass, c.bg0,
    c.warn, c.bg0,
    c.bg1, c.warn,
    s[1], s[2], s[3], s[4], s[5], s[6], s[7], s[8],
    s[9], s[10], s[11], s[12], s[13], s[14], s[15], s[16])
end

--- @param bg string
--- @return string
function M.wezterm(bg)
  local c = palette.get(bg)
  local s = ansi(c)
  local function list(from)
    local q = {}
    for i = from, from + 7 do table.insert(q, ('    "%s",'):format(s[i])) end
    return table.concat(q, "\n")
  end
  return ([[
%s
%s

[colors]
background = "%s"
foreground = "%s"
cursor_bg = "%s"
cursor_fg = "%s"
cursor_border = "%s"
selection_bg = "%s"
selection_fg = "%s"
compose_cursor = "%s"
scrollbar_thumb = "%s"
split = "%s"

ansi = [
%s
]
brights = [
%s
]

[colors.tab_bar]
background = "%s"

[colors.tab_bar.active_tab]
bg_color = "%s"
fg_color = "%s"

[colors.tab_bar.inactive_tab]
bg_color = "%s"
fg_color = "%s"

[colors.tab_bar.inactive_tab_hover]
bg_color = "%s"
fg_color = "%s"

[colors.tab_bar.new_tab]
bg_color = "%s"
fg_color = "%s"

[colors.tab_bar.new_tab_hover]
bg_color = "%s"
fg_color = "%s"

[metadata]
name = "%s"
author = "Aejkatappaja"
]]):format(
    HEADER:format(bg), GENERATED,
    c.bg0, c.fg, c.ember, c.bg0, c.ember, c.vis, c.fg, c.warn, c.bg3, c.bg3,
    list(1), list(9),
    c.bg_deep,
    c.bg0, c.fg,
    c.bg_deep, c.comment,
    c.bg1, c.fg_dim,
    c.bg_deep, c.comment,
    c.bg1, c.fg_dim,
    palette.name(bg))
end

--- KConfig INI, decimal triplets, no header comment: KDE ships these bare.
--- Faint repeats the normal colours, since the palette has no dimmed pigment.
--- @param bg string
--- @return string
function M.konsole(bg)
  local c = palette.get(bg)
  local s = ansi(c)

  local function triplet(hex)
    local r, g, b = hex:match("^#(%x%x)(%x%x)(%x%x)$")
    return ("%d,%d,%d"):format(tonumber(r, 16), tonumber(g, 16), tonumber(b, 16))
  end

  local out = {}
  local function section(name, hex)
    vim.list_extend(out, { "[" .. name .. "]", "Color=" .. triplet(hex), "" })
  end

  section("Background", c.bg0)
  section("BackgroundFaint", c.bg_deep)
  section("BackgroundIntense", c.bg1)

  for i = 1, 8 do
    local slot = "Color" .. (i - 1)
    section(slot, s[i])
    section(slot .. "Faint", s[i])
    section(slot .. "Intense", s[i + 8])
  end

  section("Foreground", c.fg)
  section("ForegroundFaint", c.fg_dim)
  section("ForegroundIntense", c.fg)

  vim.list_extend(out, {
    "[General]",
    "Description=" .. palette.name(bg),
    "Opacity=1",
    "Wallpaper=",
  })

  return table.concat(out, "\n") .. "\n"
end

--- foot takes bare hex without the leading hash.
--- @param bg string
--- @return string
function M.foot(bg)
  local c = palette.get(bg)
  local s = ansi(c)
  local bare = function(hex) return hex:sub(2) end
  local out = {
    HEADER:format(bg), GENERATED,
    "# then in foot.ini:  include=~/.config/foot/cendre.ini", "",
    "[colors]",
    ("cursor=%s %s"):format(bare(c.bg0), bare(c.ember)),
    "foreground=" .. bare(c.fg),
    "background=" .. bare(c.bg0),
    "",
  }
  for i = 1, 8 do
    table.insert(out, ("regular%d=%s"):format(i - 1, bare(s[i])))
  end
  table.insert(out, "")
  for i = 9, 16 do
    table.insert(out, ("bright%d=%s"):format(i - 9, bare(s[i])))
  end
  vim.list_extend(out, {
    "",
    "selection-foreground=" .. bare(c.fg),
    "selection-background=" .. bare(c.vis),
    "",
    ("search-box-no-match=%s %s"):format(bare(c.bg0), bare(c.error)),
    ("search-box-match=%s %s"):format(bare(c.fg), bare(c.bg3)),
    "",
    ("jump-labels=%s %s"):format(bare(c.bg0), bare(c.brass)),
    "urls=" .. bare(c.frost),
  })
  return table.concat(out, "\n") .. "\n"
end

--- iTerm2 and macOS Terminal both read this one. Components are 0 to 1 floats.
--- @param bg string
--- @return string
function M.itermcolors(bg)
  local c = palette.get(bg)
  local s = ansi(c)

  --- @param hex string
  --- @param key string
  --- @return string
  local function colour(hex, key)
    local r, g, b = hex:match("^#(%x%x)(%x%x)(%x%x)$")
    return ([[
	<key>%s</key>
	<dict>
		<key>Red Component</key><real>%.6f</real>
		<key>Green Component</key><real>%.6f</real>
		<key>Blue Component</key><real>%.6f</real>
	</dict>]]):format(key,
      tonumber(r, 16) / 255, tonumber(g, 16) / 255, tonumber(b, 16) / 255)
  end

  local body = {}
  for i, hex in ipairs(s) do
    table.insert(body, colour(hex, ("Ansi %d Color"):format(i - 1)))
  end
  vim.list_extend(body, {
    colour(c.bg0, "Background Color"),
    colour(c.fg, "Foreground Color"),
    colour(c.ember, "Cursor Color"),
    colour(c.bg0, "Cursor Text Color"),
    colour(c.vis, "Selection Color"),
    colour(c.fg, "Selected Text Color"),
    colour(c.frost, "Link Color"),
    colour(c.bg_deep, "Badge Color"),
  })

  return ([[
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
%s
</dict>
</plist>
]]):format(table.concat(body, "\n"))
end

--- Windows Terminal, as a JSON fragment: the file drops into Fragments/ whole, or
--- the object inside it goes in the `schemes` array of settings.json.
--- @param bg string
--- @return string
function M.windows_terminal(bg)
  local c = palette.get(bg)
  local slots = ansi(c)

  -- TableColorsMapping in ColorScheme.cpp, in the order ToJson writes back. Its
  -- "magenta" and "brightMagenta" are second names for slots 5 and 13, and the
  -- read loop counts keys rather than slots, so spelling one slot twice validates
  -- a scheme with another slot left on Campbell.
  local names = {
    "black", "red", "green", "yellow", "blue", "purple", "cyan", "white",
    "brightBlack", "brightRed", "brightGreen", "brightYellow",
    "brightBlue", "brightPurple", "brightCyan", "brightWhite",
  }

  local entries = {
    { "name", palette.name(bg) },
    { "cursorColor", c.ember },
    { "selectionBackground", c.vis },
    { "background", c.bg0 },
    { "foreground", c.fg },
  }
  for i, key in ipairs(names) do
    table.insert(entries, { key, slots[i] })
  end

  local body = {}
  for i, e in ipairs(entries) do
    table.insert(body, ('      "%s": "%s"%s'):format(e[1], e[2], i < #entries and "," or ""))
  end

  return ([[
{
  "schemes": [
    {
%s
    }
  ]
}
]]):format(table.concat(body, "\n"))
end

--- @param bg string
--- @return string
--- A theme block for the tokyo-night-tmux plugin, which reads its colours from a
--- case statement in its own src/themes.sh rather than from a file it can be
--- pointed at. So this is a snippet to paste there, not something tmux sources.
--- @param bg string
--- @return string
function M.tokyo_night_tmux(bg)
  local c = palette.get(bg)
  local name = palette.name(bg)

  -- The keys carry ANSI names, but the plugin never renders program output through
  -- this table: every read paints statusbar chrome. So four of them are filled by
  -- the role the plugin actually uses them for, not by the name they carry.
  local slots = {
    -- the bar's own ground, so bg2, not the editor's bg0. A statusbar sits one
    -- layer above the buffer it describes, and this theme has a step for that.
    { "background", c.bg2 },

    { "foreground", c.fg },

    -- read as a foreground, for the count of untracked files. An ANSI black there
    -- lands near 1:1 on the bar ground, which is not dim, it is gone.
    { "black", c.gutter },

    -- the plugin's accent: session block, active pane border, message bar. Ember is
    -- the accent this theme declares, and it is the only warm answer a fire has.
    { "blue", c.ember },

    { "cyan", c.terminal_cyan }, { "green", c.terminal_green },
    { "magenta", c.terminal_magenta }, { "red", c.terminal_red },

    -- foreground of the command bar, over "black" above
    { "white", c.fg },

    { "yellow", c.terminal_yellow },

    -- read as a background, under the active window block and the clock, so it has
    -- to lift off "background" above by enough to mark a state: bg4 is 0.105 of
    -- lightness clear of bg2, where bg3 would have been 0.046 and would whisper.
    -- The plugin also reads this slot as the ink of its session block, over the
    -- accent, where a fill this light only reaches 4.4:1. One value cannot serve
    -- both; the state marker is the one that carries meaning.
    { "bblack", c.bg4 },

    { "bblue", c.terminal_bright_blue },
    { "bcyan", c.terminal_bright_cyan }, { "bgreen", c.terminal_bright_green },
    { "bmagenta", c.terminal_bright_magenta }, { "bred", c.terminal_bright_red },

    -- the dim ink, since "white" above took the bright one
    { "bwhite", c.fg_dim },

    { "byellow", c.terminal_bright_yellow },
  }

  local rows = {}
  for i, slot in ipairs(slots) do
    -- the plugin's own file groups the eight normal slots then the eight bright
    if i == 11 then rows[#rows + 1] = "" end
    rows[#rows + 1] = ('    ["%s"]="%s"'):format(slot[1], slot[2])
  end

  return ([[
%s
%s
#
# The plugin reads its colours from a case statement in its own src/themes.sh, so
# paste this block there, before its default case, then in tmux.conf:
#   set -g @tokyo-night-tmux_theme "%s"
#   set -g @tokyo-night-tmux_transparent 0
#
# The transparent option is not cosmetic here: at 1 the plugin overwrites
# "background" below with tmux's "default", and the bar drops onto the terminal's
# own colour instead of the ground this theme picked for it.
#
# The keys are named after ANSI slots, but the plugin only ever paints its own
# statusbar with them, never program output. Four are filled by role instead of by
# name: "blue" is the accent, "bblack" is a block background, "black" is read as a
# foreground, and "white" is the bright ink. Aligning them to their ANSI names
# would look tidier here and worse on screen.
#
# One thing this block cannot fix: the plugin paints the inactive pane border with
# "bblack" too, the slot that fills the active window block. If that border reads
# too loud, put this in tmux.conf after the plugin runs:
#   set -g pane-border-style "fg=%s"

"%s")
  declare -A THEME=(
%s
  )
  ;;
]]):format(HEADER:format(bg), GENERATED, name, c.bg3, name, table.concat(rows, "\n"))
end

function M.tmux(bg)
  local c = palette.get(bg)
  return ([[
# cendre · %s · https://github.com/Aejkatappaja/cendre
%s
# source-file ~/.config/tmux/cendre.tmux.conf

# The bar sits on bg2, one layer above the buffer, and marks state with fills
# rather than with colour alone: the accent names the session, a bg4 fill marks the
# current window, and everything inactive stays ink on the bar's own ground.

set -g status-style "bg=%s fg=%s"
set -g status-position bottom
set -g status-justify left
set -g status-left-length 200

set -g status-left "#[fg=%s,bg=%s,bold] #{session_name} #[fg=%s,bg=%s,nobold] "
set -g status-right "#[fg=%s]#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD) "

set -g window-status-format "#[fg=%s,bg=%s] #{window_index}:#{window_name}#{window_flags} "
set -g window-status-current-format "#[fg=%s,bg=%s,bold] #{window_index}:#{window_name}#{window_flags} "
set -g window-status-last-style "fg=%s"
set -g window-status-activity-style "fg=%s"

set -g pane-border-style "fg=%s"
set -g pane-active-border-style "fg=%s"

set -g message-style "bg=%s fg=%s"
set -g message-command-style "bg=%s fg=%s"

set -g mode-style "bg=%s fg=%s"
]]):format(bg, GENERATED,
    c.bg2, c.fg,
    c.bg0, c.ember, c.fg, c.bg2,
    c.comment,
    c.comment, c.bg2,
    c.fg, c.bg4,
    c.fg_dim,
    c.warn,
    c.bg3,
    c.ember,
    c.bg2, c.fg,
    c.bg2, c.fg,
    c.vis, c.fg)
end

-- macOS Terminal stores each colour as an NSKeyedArchiver blob, base64 encoded
-- inside the plist. Every one of those blobs is byte-identical apart from a
-- 35-character RGB string, provided the three components are formatted to a fixed
-- width: the binary plist's offset table then never moves. So the archive is a
-- template with one field spliced in, rather than a plist writer.
--
-- Verified by decoding the result back through a plist parser and comparing the
-- components, not by eye.

local ARCHIVE_PREFIX = "bplist\048\048\212\001\002\003\004\005\006\021" ..
  "\024Y$archiverX$obj" ..
  "ectsT$topX$versi" ..
  "on_\016\015NSKeyedArch" ..
  "iver\163\007\008\015U$null\211\009" ..
  "\010\011\012\013\014V$class\092NSC" ..
  "olorSpaceUNSRGB\128" ..
  "\002\016\001O\016$"

local ARCHIVE_SUFFIX = "\000\210\016\017\018\019X$classesZ" ..
  "$classname\162\019\020WNS" ..
  "ColorXNSObject\209\022" ..
  "\023Troot\128\001\018\000\001\134\160\008\017\027" ..
  "$\041\050DHNU\092ioqs\154\159\168\179" ..
  "\182\190\199\202\207\209\000\000\000\000\000\000\001\001\000\000" ..
  "\000\000\000\000\000\025\000\000\000\000\000\000\000\000\000\000" ..
  "\000\000\000\000\000\214"

local B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

--- @param data string raw bytes
--- @return string base64
local function base64(data)
  local out = {}
  for i = 1, #data, 3 do
    local a, b, c = data:byte(i, i + 2)
    local n = a * 65536 + (b or 0) * 256 + (c or 0)
    local chunk = {
      B64:sub(math.floor(n / 262144) % 64 + 1, math.floor(n / 262144) % 64 + 1),
      B64:sub(math.floor(n / 4096) % 64 + 1, math.floor(n / 4096) % 64 + 1),
      b and B64:sub(math.floor(n / 64) % 64 + 1, math.floor(n / 64) % 64 + 1) or "=",
      c and B64:sub(n % 64 + 1, n % 64 + 1) or "=",
    }
    table.insert(out, table.concat(chunk))
  end
  return table.concat(out)
end

--- One archived NSColor, wrapped at 68 characters the way Terminal.app writes it.
--- @param hex string
--- @return string
local function archived(hex)
  local r, g, b = hex:match("^#(%x%x)(%x%x)(%x%x)$")
  local rgb = ("%.9f %.9f %.9f"):format(
    tonumber(r, 16) / 255, tonumber(g, 16) / 255, tonumber(b, 16) / 255)
  assert(#rgb == 35, "rgb field changed width, the template no longer applies")

  local encoded = base64(ARCHIVE_PREFIX .. rgb .. ARCHIVE_SUFFIX)
  local lines = {}
  for i = 1, #encoded, 68 do
    table.insert(lines, "\t" .. encoded:sub(i, i + 67))
  end
  return table.concat(lines, "\n")
end

--- @param bg string
--- @return string
function M.macos_terminal(bg)
  local c = palette.get(bg)
  local slots = ansi(c)
  local names = {
    "ANSIBlackColor", "ANSIRedColor", "ANSIGreenColor", "ANSIYellowColor",
    "ANSIBlueColor", "ANSIMagentaColor", "ANSICyanColor", "ANSIWhiteColor",
    "ANSIBrightBlackColor", "ANSIBrightRedColor", "ANSIBrightGreenColor",
    "ANSIBrightYellowColor", "ANSIBrightBlueColor", "ANSIBrightMagentaColor",
    "ANSIBrightCyanColor", "ANSIBrightWhiteColor",
  }

  local entries = {}
  for i, name in ipairs(names) do
    table.insert(entries, { name, slots[i] })
  end
  vim.list_extend(entries, {
    { "BackgroundColor", c.bg0 },
    { "TextColor", c.fg },
    { "BoldTextColor", c.fg },
    { "CursorColor", c.ember },
    { "SelectionColor", c.vis },
  })

  local body = {}
  for _, e in ipairs(entries) do
    table.insert(body, ("\t<key>%s</key>\n\t<data>\n%s\n\t</data>"):format(e[1], archived(e[2])))
  end

  return ([[
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
%s
	<key>Font</key>
	<data>
	YnBsaXN0MDDUAQIDBAUGGBlYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0
	b3ASAAGGoKQHCBESVSRudWxs1AkKCwwNDg8QViRjbGFzc1ZOU05hbWVWTlNTaXpl
	WE5TZkZsYWdzgAOAAiMAAAAAAAAoQBAQXxAPU0ZNb25vLVJlZ3VsYXLSExQVFlok
	Y2xhc3NuYW1lWCRjbGFzc2VzVk5TRm9udKIVF1hOU09iamVjdF8QD05TS2V5ZWRB
	cmNoaXZlctEaG1Ryb290gAEIERojLTI3O0FITltdanZ9hI2VoK2wvcbR2t3q7wAA
	AAAAAAEBAAAAAAAAABwAAAAAAAAAAAAAAAAAAAD4
	</data>
	<key>ProfileCurrentVersion</key>
	<real>2.0699999999999998</real>
	<key>name</key>
	<string>%s</string>
	<key>type</key>
	<string>Window Settings</string>
	<key>useOptionAsMetaKey</key>
	<true/>
</dict>
</plist>
]]):format(table.concat(body, "\n"), palette.name(bg))
end

return M
