local M = {}

-- Shells, prompts, pagers and TUIs. Diagnostics keep the semantic family
-- everywhere, so a failure never wears a pigment.

local palette = require("cendre.palette")

local LINK = "https://github.com/Aejkatappaja/cendre"
local GENERATED = "# generated by scripts/extras.lua, do not edit"

--- @param hex string
--- @return string "R;G;B" for an SGR truecolor sequence
local function rgb(hex)
  local r, g, b = hex:match("^#(%x%x)(%x%x)(%x%x)$")
  return ("%d;%d;%d"):format(tonumber(r, 16), tonumber(g, 16), tonumber(b, 16))
end

--- @param bg string
--- @return string
function M.fzf(bg)
  local c = palette.get(bg)
  local pairs_ = {
    { "bg+", c.bg1 }, { "bg", c.bg0 }, { "border", c.bg3 },
    { "fg", c.fg_dim }, { "fg+", c.fg }, { "gutter", c.bg0 },
    { "header", c.frost }, { "hl", c.ember }, { "hl+", c.brass },
    { "info", c.comment }, { "marker", c.ok }, { "pointer", c.ember },
    { "prompt", c.cinder }, { "query", c.fg }, { "scrollbar", c.bg3 },
    { "separator", c.bg3 }, { "spinner", c.ember },
  }
  local lines = {}
  for i, kv in ipairs(pairs_) do
    local tail = i == #pairs_ and '"' or " \\"
    table.insert(lines, ("  --color=%s:%s%s"):format(kv[1], kv[2], tail))
  end
  return ([[
# cendre theme for fzf · %s
# %s
%s
#
# Source this file from your shell rc:
#   source /path/to/extras/fzf/cendre.sh

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
%s
]]):format(bg, LINK, GENERATED, table.concat(lines, "\n"))
end

--- @param bg string
--- @return string
function M.eza(bg)
  local c = palette.get(bg)
  -- Filetype and permission keys, each mapped to a pigment by what it means:
  -- directories take the UI accent, anything executable takes the ok green,
  -- anything destructive takes the error red.
  local keys = {
    { "di", c.ember, ";1" }, { "ex", c.ok }, { "fi", c.fg }, { "ln", c.frost },
    { "or", c.error }, { "pi", c.hint }, { "so", c.frost }, { "bd", c.brass },
    { "cd", c.brass }, { "ur", c.brass }, { "uw", c.error }, { "ux", c.ok },
    { "ue", c.ok }, { "gr", c.brass }, { "gw", c.error }, { "gx", c.ok },
    { "tr", c.brass }, { "tw", c.error }, { "tx", c.ok }, { "su", c.cinder },
    { "sf", c.cinder }, { "xa", c.comment }, { "sn", c.fg }, { "sb", c.fg_dim },
    { "uu", c.brass }, { "un", c.fg_dim }, { "gu", c.ember }, { "gn", c.fg_dim },
    { "da", c.comment }, { "in", c.gutter }, { "lc", c.comment }, { "lp", c.frost },
    { "ga", c.ok }, { "gm", c.info }, { "gd", c.error }, { "gv", c.frost },
    { "gt", c.brass }, { "gi", c.gutter }, { "gc", c.warn }, { "hd", c.fg, ";1" },
  }
  local lines = {}
  for i, k in ipairs(keys) do
    local tail = i == #keys and '"' or ":\\"
    table.insert(lines, ("%s=38;2;%s%s%s"):format(k[1], rgb(k[2]), k[3] or "", tail))
  end
  return ([[
# cendre theme for eza (https://eza.rocks) · %s
# %s
%s
#
# Install: source this file from your shell rc.
#   source /path/to/extras/eza/cendre.sh

export EZA_COLORS="\
%s
]]):format(bg, LINK, GENERATED, table.concat(lines, "\n"))
end

--- @param bg string
--- @return string
function M.delta(bg)
  local c = palette.get(bg)
  return ([[
# cendre theme for delta (git-delta) · %s
# %s
%s
#
# Add to your .gitconfig:
#   [include]
#     path = /path/to/extras/delta/cendre.gitconfig
#
# For syntax highlighting, install the bat theme too:
#   cp /path/to/extras/bat/cendre.tmTheme "$(bat --config-dir)/themes/"
#   bat cache --build

[delta]
  syntax-theme = %s
  minus-style = syntax "%s"
  minus-emph-style = syntax bold "%s"
  plus-style = syntax "%s"
  plus-emph-style = syntax bold "%s"
  hunk-header-style = "%s" italic
  hunk-header-decoration-style = "%s" box
  file-style = "%s" bold
  file-decoration-style = "%s" ul
  line-numbers-minus-style = "%s"
  line-numbers-plus-style = "%s"
  line-numbers-zero-style = "%s"
  line-numbers-left-style = "%s"
  line-numbers-right-style = "%s"
  commit-decoration-style = "%s" box
  commit-style = "%s" bold
  blame-palette = "%s" "%s" "%s" "%s"
]]):format(bg, LINK, GENERATED,
    palette.name(bg),
    c.del, c.bg3, c.add, c.bg3,
    c.fg_dim, c.bg3,
    c.frost, c.frost,
    c.error, c.ok, c.gutter, c.gutter, c.gutter,
    c.ember, c.brass,
    c.bg0, c.bg1, c.bg2, c.bg3)
end

--- @param bg string
--- @return string
function M.lazygit(bg)
  local c = palette.get(bg)
  return ([[
# cendre · %s · %s
%s
# Merge into ~/.config/lazygit/config.yml

gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "%s"
      - "bold"
    inactiveBorderColor:
      - "%s"
    searchingActiveBorderColor:
      - "%s"
      - "bold"
    optionsTextColor:
      - "%s"
    selectedLineBgColor:
      - "%s"
    inactiveViewSelectedLineBgColor:
      - "%s"
    cherryPickedCommitFgColor:
      - "%s"
    cherryPickedCommitBgColor:
      - "%s"
    markedBaseCommitFgColor:
      - "%s"
    markedBaseCommitBgColor:
      - "%s"
    unstagedChangesColor:
      - "%s"
    defaultFgColor:
      - "%s"
]]):format(bg, LINK, GENERATED,
    c.ember, c.comment, c.brass, c.ember,
    c.bg2, c.bg1,
    c.bg0, c.ember,
    c.bg0, c.brass,
    c.error, c.fg)
end

--- @param bg string
--- @return string
function M.btop(bg)
  local c = palette.get(bg)
  return ([[
# cendre theme for btop · %s
# %s
%s

theme[main_bg]="%s"
theme[main_fg]="%s"
theme[title]="%s"
theme[hi_fg]="%s"
theme[selected_bg]="%s"
theme[selected_fg]="%s"
theme[inactive_fg]="%s"
theme[graph_text]="%s"
theme[meter_bg]="%s"

theme[proc_misc]="%s"
theme[cpu_box]="%s"
theme[mem_box]="%s"
theme[net_box]="%s"
theme[proc_box]="%s"
theme[div_line]="%s"

# temperature runs cool to hot, so it borrows the palette's own order
theme[temp_start]="%s"
theme[temp_mid]="%s"
theme[temp_end]="%s"

theme[cpu_start]="%s"
theme[cpu_mid]="%s"
theme[cpu_end]="%s"

theme[free_start]="%s"
theme[free_mid]="%s"
theme[free_end]="%s"

theme[cached_start]="%s"
theme[cached_mid]="%s"
theme[cached_end]="%s"

theme[available_start]="%s"
theme[available_mid]="%s"
theme[available_end]="%s"

theme[used_start]="%s"
theme[used_mid]="%s"
theme[used_end]="%s"

theme[download_start]="%s"
theme[download_mid]="%s"
theme[download_end]="%s"

theme[upload_start]="%s"
theme[upload_mid]="%s"
theme[upload_end]="%s"

theme[process_start]="%s"
theme[process_mid]="%s"
theme[process_end]="%s"
]]):format(bg, LINK, GENERATED,
    c.bg0, c.fg, c.fg, c.ember, c.bg2, c.fg, c.comment, c.fg_dim, c.bg3,
    c.ember, c.ember, c.frost, c.sap, c.brass, c.bg3,
    c.frost, c.brass, c.cinder,
    c.frost, c.brass, c.cinder,
    c.sap, c.sap, c.ok,
    c.frost, c.frost, c.hint,
    c.brass, c.ember, c.brass,
    c.frost, c.ember, c.cinder,
    c.frost, c.hint, c.frost,
    c.ember, c.brass, c.ember,
    c.ember, c.sap, c.ok)
end

--- @param bg string
--- @return string
function M.yazi(bg)
  local c = palette.get(bg)

  --- @param body string the inside of an inline table, without the braces
  --- @return string
  local function tbl(body)
    return "{ " .. body .. " }"
  end

  --- @param fg string|nil
  --- @param bg_ string|nil
  --- @param flags string|nil
  --- @return string an inline table for one theme key
  local function style(fg, bg_, flags)
    local parts = {}
    if fg then parts[#parts + 1] = ('fg = "%s"'):format(fg) end
    if bg_ then parts[#parts + 1] = ('bg = "%s"'):format(bg_) end
    if flags then parts[#parts + 1] = flags end
    return tbl(table.concat(parts, ", "))
  end

  -- Every section and key below is taken from yazi's own preset theme, not from
  -- an older theme carried forward. This file used to write [manager] and
  -- [select], which no longer exist: yazi renamed them [mgr] and [pick], and
  -- moved the tab, mode and hovered keys out into [tabs], [mode] and
  -- [indicator]. An unknown section is ignored rather than refused, so half the
  -- file applied and nothing said which half.
  --
  -- theme.toml merges over the preset, so only what carries colour is written
  -- here. Glyphs, separators, column counts and the icon table stay yazi's.
  local sections = {
    { "mgr", {
      { "cwd", style(c.ember) },
      { "find_keyword", style(c.brass, nil, "bold = true") },
      { "find_position", style(c.ember, nil, "italic = true") },
      { "symlink_target", style(c.fg_dim, nil, "italic = true") },

      -- The markers are the thin bar down the left of a flagged row, so both
      -- channels carry the same colour: yazi paints the cell, not a glyph.
      { "marker_copied", style(c.ok, c.ok) },
      { "marker_cut", style(c.error, c.error) },
      { "marker_marked", style(c.info, c.info) },
      { "marker_selected", style(c.ember, c.ember) },

      -- The counts sit on those colours, so they take the ground rather than ink
      { "count_copied", style(c.bg0, c.ok) },
      { "count_cut", style(c.bg0, c.error) },
      { "count_selected", style(c.bg0, c.ember) },

      { "border_style", style(c.bg3) },
    } },

    -- The dim ink goes on bg1, never on bg2. That is the pairing the lualine
    -- theme already uses: fg on bg2, fg_dim on bg1. On bg2 at the soft depth
    -- fg_dim reads 4.27:1, which would be a fourth quiet colour the rules do
    -- not name.
    { "tabs", {
      { "active", style(c.bg0, c.ember, "bold = true") },
      { "inactive", style(c.fg_dim, c.bg1) },
    } },

    { "mode", {
      { "normal_main", style(c.bg0, c.ember, "bold = true") },
      { "normal_alt", style(c.ember, c.bg2) },
      { "select_main", style(c.bg0, c.info, "bold = true") },
      { "select_alt", style(c.info, c.bg2) },
      -- Unset is the inverse of select, not a failure, so it takes the caution
      -- colour. Error on the statusline layer would also land under AA at every
      -- depth, where warn clears it at 6.11:1 on the lightest ground.
      { "unset_main", style(c.bg0, c.warn, "bold = true") },
      { "unset_alt", style(c.warn, c.bg2) },
    } },

    -- The hovered row in each of the three panes. The preset reverses it, which
    -- is louder than anything else on screen; bg1 is the layer this palette
    -- already uses for a cursor line.
    { "indicator", {
      { "parent", style(nil, c.bg1) },
      { "current", style(nil, c.bg1) },
      { "preview", style(nil, c.bg1) },
    } },

    { "status", {
      { "overall", style(c.fg, c.bg2) },
      { "perm_sep", style(c.gutter) },
      { "perm_type", style(c.frost) },
      { "perm_read", style(c.brass) },
      { "perm_write", style(c.error) },
      { "perm_exec", style(c.sap) },
      { "progress_label", style(c.fg, nil, "bold = true") },
      { "progress_normal", style(c.ember, c.bg2) },
      -- A badge rather than coloured text, which is the shape yazi's own preset
      -- uses here, and the only one that keeps error at its published ratio
      -- instead of losing 0.8 to the lighter statusline ground.
      { "progress_error", style(c.bg0, c.error) },
    } },

    { "which", {
      { "mask", style(nil, c.bg_deep) },
      { "cand", style(c.ember) },
      { "rest", style(c.comment) },
      { "desc", style(c.fg_dim) },
      { "separator_style", style(c.bg3) },
    } },

    { "confirm", {
      { "border", style(c.bg3) },
      { "title", style(c.ember) },
      { "body", style(c.fg) },
      { "list", style(c.fg_dim) },
      { "btn_yes", style(c.bg0, c.ember, "bold = true") },
      { "btn_no", style(c.fg_dim) },
    } },

    { "spot", {
      { "border", style(c.bg3) },
      { "title", style(c.ember) },
      { "tbl_col", style(c.frost) },
      { "tbl_cell", style(c.bg0, c.ember) },
    } },

    { "notify", {
      { "title_info", style(c.info) },
      { "title_warn", style(c.warn) },
      { "title_error", style(c.error) },
    } },

    { "pick", {
      { "border", style(c.bg3) },
      { "active", style(c.ember, nil, "bold = true") },
      { "inactive", style(c.fg_dim) },
    } },

    { "input", {
      { "border", style(c.bg3) },
      { "title", style(c.ember) },
      { "value", style(c.fg) },
      { "selected", style(nil, c.vis) },
    } },

    { "cmp", {
      { "border", style(c.bg3) },
      { "active", style(c.bg0, c.ember) },
      { "inactive", style(c.fg_dim) },
    } },

    { "tasks", {
      { "border", style(c.bg3) },
      { "title", style(c.ember) },
      { "hovered", style(c.ember, nil, "bold = true") },
    } },

    { "help", {
      { "on", style(c.ember) },
      { "run", style(c.brass) },
      { "desc", style(c.fg_dim) },
      { "hovered", style(nil, c.bg1, "bold = true") },
      { "footer", style(c.fg_dim, c.bg1) },
    } },
  }

  local out = {
    ("# cendre theme for Yazi · %s"):format(bg),
    "# " .. LINK,
    GENERATED,
    "#",
    "# The file preview highlights code through syntect, which reads a tmTheme",
    "# rather than any key below. To put this palette there too:",
    "#   cp extras/bat/cendre.tmTheme ~/.config/yazi/",
    '#   then add syntect_theme = "cendre.tmTheme" under [mgr]',
    "# It is not written here because a path that does not resolve leaves",
    "# previews unhighlighted with no message.",
  }

  for _, section in ipairs(sections) do
    out[#out + 1] = ""
    out[#out + 1] = ("[%s]"):format(section[1])
    for _, pair in ipairs(section[2]) do
      out[#out + 1] = ("%s = %s"):format(pair[1], pair[2])
    end
  end

  -- The rule kinds are yazi's: a mime glob, a url glob, or one of its `is`
  -- states. What each kind is worth is this palette's call. Language by
  -- extension is deliberately absent: no derivation makes Go blue and Python
  -- green, and a colour nobody can trace is the one thing this theme does not
  -- ship.
  local rules = {
    { "# Image", ('{ mime = "image/*", fg = "%s" }'):format(c.brass) },
    { "# Media", ('{ mime = "{audio,video}/*", fg = "%s" }'):format(c.terminal_magenta) },
    { "# Archive", ('{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "%s" }'):format(c.cinder) },
    { "# Document", ('{ mime = "application/{pdf,doc,rtf}", fg = "%s" }'):format(c.frost) },
    { "# Virtual file system", ('{ mime = "vfs/{absent,stale}", fg = "%s" }'):format(c.comment) },
    { "# Broken link, and a file yazi could not read", ('{ url = "*", is = "orphan", bg = "%s" }'):format(c.error) },
    { nil, ('{ url = "*", is = "dummy", bg = "%s" }'):format(c.error) },
    { nil, ('{ url = "*/", is = "dummy", bg = "%s" }'):format(c.error) },
    { "# Executable", ('{ url = "*", is = "exec", fg = "%s" }'):format(c.sap) },
    { "# Directory, last so the globs above win", ('{ url = "*/", fg = "%s" }'):format(c.ember) },
  }

  out[#out + 1] = ""
  out[#out + 1] = "[filetype]"
  out[#out + 1] = "rules = ["
  for i, rule in ipairs(rules) do
    if rule[1] then out[#out + 1] = "  " .. rule[1] end
    out[#out + 1] = "  " .. rule[2] .. (i < #rules and "," or "")
  end
  out[#out + 1] = "]"

  return table.concat(out, "\n") .. "\n"
end

--- @param bg string
--- @return string
function M.opencode(bg)
  local c = palette.get(bg)
  local defs = {
    { "bg", c.bg0 }, { "bgFloat", c.bg_deep }, { "bgElevated", c.bg1 },
    { "bgCursorline", c.bg1 }, { "bgSelection", c.vis }, { "border", c.bg3 },
    { "fg", c.fg }, { "fgDim", c.fg_dim }, { "fgComment", c.comment },
    { "fgGutter", c.gutter },
    { "cinder", c.cinder }, { "ember", c.ember }, { "brass", c.brass },
    { "sap", c.sap }, { "frost", c.frost },
    { "error", c.error }, { "warning", c.warn }, { "success", c.ok },
    { "info", c.info }, { "hint", c.hint },
    { "gitAdd", c.ok }, { "gitDelete", c.error }, { "gitChange", c.info },
    -- The tinted line grounds. Without these the added and the removed row both
    -- landed on bgElevated, which is one background for two opposite things.
    { "bgAdd", c.add }, { "bgDel", c.del },
  }
  local uses = {
    { "primary", "ember" }, { "secondary", "frost" }, { "accent", "brass" },
    { "text", "fg" }, { "textMuted", "fgDim" },
    { "background", "bg" }, { "backgroundPanel", "bgFloat" },
    { "backgroundElement", "bgElevated" },

    -- Both optional, and opencode falls back for them: the selected row's text to
    -- background, which its own comment calls backward compatibility, and the menu
    -- to backgroundElement. Set outright rather than left to a legacy path, and the
    -- menu takes the float surface, the layer this palette gives anything drawn
    -- over the editor.
    { "selectedListItemText", "bg" }, { "backgroundMenu", "bgFloat" },
    { "border", "border" }, { "borderActive", "ember" }, { "borderSubtle", "border" },
    { "error", "error" }, { "warning", "warning" }, { "success", "success" },
    { "info", "info" },
    { "diffAdded", "gitAdd" }, { "diffRemoved", "gitDelete" },
    { "diffContext", "fgDim" }, { "diffHunkHeader", "fgComment" },
    { "diffHighlightAdded", "success" }, { "diffHighlightRemoved", "error" },
    { "diffAddedBg", "bgAdd" }, { "diffRemovedBg", "bgDel" },
    { "diffContextBg", "bg" }, { "diffLineNumber", "fgGutter" },
    { "diffAddedLineNumberBg", "bgAdd" }, { "diffRemovedLineNumberBg", "bgDel" },
    { "markdownText", "fg" }, { "markdownHeading", "ember" },
    { "markdownLink", "frost" }, { "markdownLinkText", "frost" },
    { "markdownCode", "sap" }, { "markdownBlockQuote", "fgComment" },
    { "markdownEmph", "ember" }, { "markdownStrong", "brass" },
    { "markdownHorizontalRule", "border" }, { "markdownListItem", "ember" },
    -- An ordered marker is the same role as a bullet, and an image is a target
    -- like a link, so each follows the one it belongs with.
    { "markdownListEnumeration", "ember" },
    { "markdownImage", "frost" }, { "markdownImageText", "frost" },
    { "markdownCodeBlock", "sap" },
    { "syntaxComment", "fgComment" }, { "syntaxKeyword", "cinder" },
    { "syntaxFunction", "brass" }, { "syntaxVariable", "fg" },
    { "syntaxString", "sap" }, { "syntaxNumber", "sap" },
    { "syntaxType", "frost" }, { "syntaxOperator", "fgDim" },
    { "syntaxPunctuation", "fgDim" },
  }

  local dl, ul = {}, {}
  for i, d in ipairs(defs) do
    table.insert(dl, ('    "%s": "%s"%s'):format(d[1], d[2], i < #defs and "," or ""))
  end
  for i, u in ipairs(uses) do
    table.insert(ul, ('    "%s": "%s"%s'):format(u[1], u[2], i < #uses and "," or ""))
  end

  return ([[
{
  "$schema": "https://opencode.ai/theme.json",
  "defs": {
%s
  },
  "theme": {
%s
  }
}
]]):format(table.concat(dl, "\n"), table.concat(ul, "\n"))
end

--- @param bg string
--- @return string
function M.hunk(bg)
  local c = palette.get(bg)

  -- The key names and their order come from CUSTOM_THEME_COLOR_KEYS in Hunk's
  -- own parser, which is the only exhaustive list. It iterates that constant and
  -- ignores anything else without a word, so the four keys this file used to
  -- write that are not in it, added, removed, context and lineNumber, were
  -- dropped in silence.
  local colors = {
    { "background", c.bg0 },
    { "panel", c.bg_deep },
    { "panelAlt", c.bg1 },
    { "border", c.bg3 },
    { "accent", c.ember },
    { "accentMuted", c.fg_dim },
    { "text", c.fg },
    { "muted", c.comment },

    -- Line grounds. The moved pair keeps the changed tint on the destination and
    -- leaves the source neutral, since a moved block is one event with a
    -- direction rather than an addition and a deletion.
    { "addedBg", c.add },
    { "removedBg", c.del },
    { "movedAddedBg", c.mod },
    { "movedRemovedBg", c.bg2 },
    { "contextBg", c.bg0 },

    -- The word-level ground inside a changed line. This is the layer, not a
    -- stronger tint: the same answer DiffText and the GitSigns inline groups
    -- already give in the editor, so a diff reads the same in both.
    { "addedContentBg", c.bg3 },
    { "removedContentBg", c.bg3 },
    { "contextContentBg", c.bg1 },

    { "addedSignColor", c.ok },
    { "removedSignColor", c.error },
    { "lineNumberBg", c.bg_deep },
    { "lineNumberFg", c.gutter },
    { "selectedHunk", c.vis },

    { "badgeAdded", c.ok },
    { "badgeRemoved", c.error },
    { "badgeNeutral", c.fg_dim },

    -- File states are a status, so they take the semantic family rather than a
    -- pigment: nothing in a file list should wear the same colour as a keyword.
    { "fileNew", c.ok },
    { "fileDeleted", c.error },
    { "fileRenamed", c.info },
    { "fileModified", c.warn },
    { "fileUntracked", c.comment },

    { "noteBorder", c.bg3 },
    { "noteBackground", c.bg_deep },
    { "noteTitleBackground", c.bg2 },
    { "noteTitleText", c.fg },
  }

  -- The syntax side is written twice on purpose, which is the migration shape
  -- Hunk documents. The released version, 0.17.7, only reads the flat role table
  -- and never looks at syntax_scopes. Its successor deprecates the role table and
  -- translates it approximately. Writing both means the theme is exact on the
  -- version that has scopes and correct on the version people actually have, and
  -- neither errors on the other's table: Hunk reads the keys it knows and ignores
  -- the rest. Drop the role table once scopes ship in a release.
  --
  -- These are the eleven roles the released parser reads, and they are also the
  -- roles cendre's own map is written in, so this half needs no translation.
  local roles = {
    { "default", c.fg },
    { "keyword", c.cinder },
    { "string", c.sap },
    { "comment", c.comment },
    { "number", c.sap },
    { "function", c.brass },
    { "property", c.ember },
    { "type", c.frost },
    { "variable", c.fg },
    { "operator", c.fg_dim },
    { "punctuation", c.fg_dim },
  }

  --
  -- The selectors for each role are the ones Hunk's own migration adapter maps
  -- that role onto, which keeps this agreeing with its idea of equivalence
  -- rather than inventing a second one. The extra specific selectors exist
  -- because a narrower selector in the base theme beats a broader override here.
  local scopes = {
    { "source", c.fg },

    { "comment", c.comment },
    { "punctuation.definition.comment", c.comment },

    { "keyword", c.cinder },
    { "keyword.control", c.cinder },
    { "storage", c.cinder },
    { "storage.type", c.cinder },
    { "storage.modifier", c.cinder },

    -- Punctuation is not a token, so operators and brackets take the dim ink
    { "keyword.operator", c.fg_dim },
    { "punctuation", c.fg_dim },

    { "string", c.sap },
    { "constant.numeric", c.sap },
    { "constant.language", c.sap },

    { "entity.name.function", c.brass },
    { "support.function", c.brass },
    { "variable.function", c.brass },

    { "entity.name.type", c.frost },
    { "entity.name.class", c.frost },
    { "support.type", c.frost },
    { "support.class", c.frost },

    -- A declared name is not a role: variables and constant names stay in the
    -- body ink, and only what they hold takes a pigment.
    { "variable", c.fg },
    { "variable.other.constant", c.fg },

    { "variable.other.property", c.ember },
    { "support.variable.property", c.ember },
    { "variable.parameter", c.ember },
  }

  local out = {
    ("# cendre theme for Hunk · %s"):format(bg),
    "# " .. LINK,
    GENERATED,
    "#",
    "# Install: copy into ~/.config/hunk/config.toml, or merge the three",
    '# [custom_theme] tables below and set `theme = "custom"`.',
    "",
    'theme = "custom"',
    "",
    "[custom_theme]",
    'base  = "github-dark-default"  # only supplies scopes not overridden below',
    ('label = "%s"'):format(palette.name(bg)),
    "",
  }

  local width = 0
  for _, pair in ipairs(colors) do
    width = math.max(width, #pair[1])
  end
  for _, pair in ipairs(colors) do
    out[#out + 1] = ("%-" .. width .. 's = "%s"'):format(pair[1], pair[2])
  end

  out[#out + 1] = ""
  out[#out + 1] = "# Read by Hunk 0.17.7 and deprecated in its successor."
  out[#out + 1] = "[custom_theme.syntax]"
  for _, pair in ipairs(roles) do
    out[#out + 1] = ('%s = "%s"'):format(pair[1], pair[2])
  end

  out[#out + 1] = ""
  out[#out + 1] = "# Read by Hunk after 0.17.7, and wins over the table above."
  out[#out + 1] = "[custom_theme.syntax_scopes]"
  for _, pair in ipairs(scopes) do
    out[#out + 1] = ('"%s" = "%s"'):format(pair[1], pair[2])
  end

  return table.concat(out, "\n") .. "\n"
end

--- @param bg string
--- @return string
function M.herdr(bg)
  local c = palette.get(bg)
  return ([[
# cendre theme for herdr (https://herdr.dev) · %s
# %s
%s
#
# Install: copy into ~/.config/herdr/config.toml, or merge the [theme] and
# [theme.custom] blocks below into your existing config.

[theme]
name = "terminal"   # neutral base; every token below is overridden by cendre
auto_switch = false

[theme.custom]
accent      = "%s"
panel_bg    = "%s"
surface0    = "%s"
surface1    = "%s"
surface_dim = "%s"
overlay0    = "%s"
overlay1    = "%s"
text        = "%s"
subtext0    = "%s"
mauve       = "%s"
green       = "%s"
yellow      = "%s"
red         = "%s"
blue        = "%s"
teal        = "%s"
peach       = "%s"
]]):format(bg, LINK, GENERATED,
    c.ember, c.bg0, c.bg1, c.bg2, c.bg_deep,
    c.comment, c.fg_dim, c.fg, c.fg_dim,
    c.cinder, c.sap, c.brass, c.error, c.frost, c.hint, c.ember)
end

--- @param bg string
--- @return string
function M.starship(bg)
  local c = palette.get(bg)
  return ([[
# cendre palette for Starship · %s
# %s
%s
#
# Install: copy into ~/.config/starship.toml, or if you keep your own config,
# copy the [palettes.%s] block and add `palette = "%s"` at the top.

palette = "%s"

[palettes.%s]
bg      = "%s"
fg      = "%s"
fg_dim  = "%s"
comment = "%s"
cinder  = "%s"
ember   = "%s"
brass   = "%s"
sap     = "%s"
frost   = "%s"
error   = "%s"
warning = "%s"
ok      = "%s"
info    = "%s"

[directory]
style = "ember bold"

[git_branch]
style = "cinder"

[git_status]
style = "warning"

[cmd_duration]
style = "comment"

[character]
success_symbol = "[❯](ember)"
error_symbol = "[❯](error)"
vimcmd_symbol = "[❮](sap)"

[nodejs]
style = "sap"

[golang]
style = "frost"

[rust]
style = "cinder"

[python]
style = "brass"

[lua]
style = "frost"
]]):format(bg, LINK, GENERATED,
    palette.name(bg), palette.name(bg),
    palette.name(bg), palette.name(bg),
    c.bg0, c.fg, c.fg_dim, c.comment,
    c.cinder, c.ember, c.brass, c.sap, c.frost,
    c.error, c.warn, c.ok, c.info)
end

--- Slack takes ten comma-separated hex values in a fixed order.
--- @param bg string
--- @return string
function M.slack(bg)
  local c = palette.get(bg)
  return table.concat({
    c.bg0,   -- column bg
    c.bg_deep, -- menu bg
    c.ember, -- active item
    c.bg0,   -- active item text
    c.bg2,   -- hover item
    c.fg,    -- text
    c.ok,    -- active presence
    c.error, -- mention badge
    c.bg0,   -- top nav bg
    c.fg,    -- top nav text
  }, ",") .. "\n"
end

--- A Plasma colour scheme, shaped like BreezeDark.colors. The eight sections are a
--- ladder of depth, so only the two grounds move.
--- @param bg string
--- @return string
function M.kde(bg)
  local c = palette.get(bg)

  local function triplet(hex)
    local r, g, b = hex:match("^#(%x%x)(%x%x)(%x%x)$")
    return ("%d,%d,%d"):format(tonumber(r, 16), tonumber(g, 16), tonumber(b, 16))
  end

  -- Plasma fills with hover and focus, so both are ground steps.
  local ink = {
    DecorationFocus = c.bg4,
    DecorationHover = c.bg3,
    ForegroundActive = c.ember,
    ForegroundInactive = c.fg_dim,
    ForegroundLink = c.info,
    ForegroundNegative = c.error,
    ForegroundNeutral = c.warn,
    ForegroundNormal = c.fg,
    ForegroundPositive = c.ok,
    ForegroundVisited = c.potassium_bright,
  }

  local out = {}
  -- Keys sorted: pairs() has no order, and two renders must not differ.
  local function section(name, normal, alternate, override)
    local keys = vim.tbl_extend("force", {
      BackgroundNormal = normal,
      BackgroundAlternate = alternate,
    }, ink, override or {})

    local lines = {}
    for key, hex in pairs(keys) do
      table.insert(lines, key .. "=" .. triplet(hex))
    end
    table.sort(lines)

    table.insert(out, "[" .. name .. "]")
    vim.list_extend(out, lines)
    table.insert(out, "")
  end

  -- alternates go down, not up: every ink here is light
  section("Colors:Button", c.bg2, c.bg1)
  section("Colors:Complementary", c.bg_deep, c.bg1)
  section("Colors:Header", c.bg2, c.bg1)
  section("Colors:Header][Inactive", c.bg1, c.bg2)
  -- Accent fill, so every ink flips dark and the two fills go lighter instead.
  local dark = {
    ForegroundInactive = c.bg2,
    DecorationHover = c.brass,
    DecorationFocus = c.fg,
  }
  for key in pairs(ink) do
    dark[key] = dark[key] or c.bg0
  end
  section("Colors:Selection", c.ember, c.brass, dark)
  section("Colors:Tooltip", c.bg_deep, c.bg1)
  section("Colors:View", c.bg_deep, c.bg0)
  section("Colors:Window", c.bg0, c.bg1)

  vim.list_extend(out, {
    "[WM]",
    "activeBackground=" .. triplet(c.bg2),
    "activeBlend=" .. triplet(c.fg),
    "activeForeground=" .. triplet(c.fg),
    "inactiveBackground=" .. triplet(c.bg1),
    "inactiveBlend=" .. triplet(c.comment),
    "inactiveForeground=" .. triplet(c.comment),
    "",
    "[General]",
    "ColorScheme=" .. palette.name(bg),
    "Name=" .. palette.name(bg),
    "shadeSortColumn=true",
    "",
    "[KDE]",
    "contrast=4",
  })

  return table.concat(out, "\n") .. "\n"
end

--- @param bg string
--- @return string
function M.obsidian(bg)
  local c = palette.get(bg)

  --- The accent as HSL components, which Obsidian derives several elements from
  --- rather than reading the hex. Computed here so it cannot drift from ember.
  --- @param hex string
  --- @return integer h, integer s, integer l
  local function hsl(hex)
    local r = tonumber(hex:sub(2, 3), 16) / 255
    local g = tonumber(hex:sub(4, 5), 16) / 255
    local b = tonumber(hex:sub(6, 7), 16) / 255
    local hi, lo = math.max(r, g, b), math.min(r, g, b)
    local l = (hi + lo) / 2
    if hi == lo then return 0, 0, math.floor(l * 100 + 0.5) end
    local d = hi - lo
    local s = l > 0.5 and d / (2 - hi - lo) or d / (hi + lo)
    local h
    if hi == r then h = (g - b) / d + (g < b and 6 or 0)
    elseif hi == g then h = (b - r) / d + 2
    else h = (r - g) / d + 4 end
    return math.floor(h * 60 + 0.5), math.floor(s * 100 + 0.5), math.floor(l * 100 + 0.5)
  end

  --- @param hex string
  --- @return string the three channels, for a variable Obsidian wants as rgb
  local function channels(hex)
    return ("%d, %d, %d"):format(
      tonumber(hex:sub(2, 3), 16), tonumber(hex:sub(4, 5), 16), tonumber(hex:sub(6, 7), 16))
  end

  local h, s, l = hsl(c.ember)

  -- Every variable, as ordered pairs rather than one positional template: at
  -- 147 of them a format string means an inserted line silently shifts every
  -- colour after it onto its neighbour's variable.
  local vars = {
    { "--background-primary", c.bg0 },
    { "--background-primary-alt", c.bg1 },
    { "--background-secondary", c.bg_deep },
    { "--background-secondary-alt", c.bg1 },
    { "--background-modifier-border", c.bg3 },
    { "--background-modifier-border-hover", c.bg4 },
    { "--background-modifier-hover", c.bg1 },
    { "--background-modifier-error", c.del },
    { "--background-modifier-success", c.add },
    { "--text-normal", c.fg },
    { "--text-muted", c.fg_dim },
    { "--text-faint", c.comment },
    { "--text-accent", c.ember },
    { "--text-accent-hover", c.brass },
    { "--text-on-accent", c.bg0 },
    { "--text-selection", c.vis },
    { "--text-highlight-bg", c.vis },
    { "--text-error", c.error },
    { "--text-success", c.ok },
    { "--interactive-accent", c.ember },
    { "--interactive-accent-hover", c.brass },
    { "--interactive-normal", c.bg2 },
    { "--interactive-hover", c.bg3 },
    { "--h1-color", c.ember },
    { "--h2-color", c.brass },
    { "--h3-color", c.frost },
    { "--h4-color", c.sap },
    { "--h5-color", c.cinder },
    { "--h6-color", c.fg_dim },
    { "--code-normal", c.fg },
    { "--code-background", c.bg_deep },
    { "--code-keyword", c.cinder },
    { "--code-function", c.brass },
    { "--code-string", c.sap },
    { "--code-value", c.sap },
    { "--code-comment", c.comment },
    { "--code-property", c.ember },
    { "--code-tag", c.cinder },
    { "--code-operator", c.fg_dim },
    { "--blockquote-border-color", c.ember },
    { "--hr-color", c.bg3 },
    { "--tag-color", c.frost },
    { "--tag-background", c.bg1 },
    { "--checkbox-color", c.ember },
    { "--link-color", c.frost },
    { "--link-unresolved-color", c.error },
    { "--graph-line", c.bg3 },
    { "--graph-node", c.ember },
    { "--graph-node-tag", c.frost },

    -- accent
    { "--color-accent", c.ember },
    { "--color-accent-1", c.brass },
    { "--color-accent-2", c.cinder },

    -- surfaces and dividers
    { "--background-modifier-cover", c.bg_deep },
    { "--background-modifier-box-shadow", c.bg_deep },
    { "--background-modifier-form-field", c.bg1 },
    { "--background-modifier-form-field-highlighted", c.bg2 },
    { "--background-modifier-error-hover", c.error },
    { "--divider-color", c.bg3 },
    { "--divider-color-hover", c.ember },
    { "--indentation-guide-color", c.bg3 },
    { "--indentation-guide-color-active", c.bg5 },
    { "--flashing-background", c.vis },

    -- text
    { "--bold-color", c.fg },
    { "--italic-color", c.fg },
    { "--text-error-hover", c.error },
    { "--text-highlight-bg-active", c.vis },
    { "--text-on-accent-inverted", c.fg },

    -- links
    { "--link-color-hover", c.brass },
    { "--link-external-color", c.frost },
    { "--link-external-color-hover", c.brass },

    -- inline code
    { "--inline-code-color", c.sap },
    { "--inline-code-background", c.bg1 },
    { "--code-important", c.cinder },

    -- lists and checkboxes
    { "--list-marker-color", c.ember },
    { "--list-marker-color-hover", c.brass },
    { "--list-marker-color-collapsed", c.cinder },
    { "--checkbox-border-color", c.gutter },
    { "--checkbox-border-color-hover", c.ember },
    { "--checkbox-color-hover", c.brass },

    -- icons
    { "--icon-color", c.fg_dim },
    { "--icon-color-hover", c.fg },
    { "--icon-color-active", c.ember },
    { "--icon-color-focused", c.fg },

    -- callouts, on the semantic family so an admonition never wears a syntax pigment
    { "--callout-default", c.info },
    { "--callout-info", c.info },
    { "--callout-todo", c.info },
    { "--callout-tip", c.ok },
    { "--callout-success", c.ok },
    { "--callout-question", c.hint },
    { "--callout-warning", c.warn },
    { "--callout-fail", c.error },
    { "--callout-error", c.error },
    { "--callout-bug", c.error },
    { "--callout-example", c.frost },
    { "--callout-quote", c.comment },

    -- blockquotes
    { "--blockquote-background-color", c.bg1 },

    -- navigation
    { "--nav-item-color", c.fg_dim },
    { "--nav-item-color-hover", c.fg },
    { "--nav-item-color-active", c.fg },
    { "--nav-item-background-hover", c.bg1 },
    { "--nav-item-background-active", c.bg2 },
    { "--nav-heading-color", c.ember },
    { "--nav-heading-color-collapsed", c.fg_dim },
    { "--nav-indentation-guide-color", c.bg3 },
    { "--vault-name-color", c.ember },
    { "--ribbon-background", c.bg_deep },
    { "--ribbon-background-collapsed", c.bg_deep },

    -- tabs
    { "--tab-background-active", c.bg0 },
    { "--tab-text-color", c.fg_dim },
    { "--tab-text-color-focused", c.fg_dim },
    { "--tab-text-color-focused-active", c.fg },
    { "--tab-text-color-focused-active-current", c.ember },
    { "--tab-divider-color", c.bg3 },
    { "--tab-outline-color", c.bg3 },

    -- title bar and status bar
    { "--titlebar-background", c.bg_deep },
    { "--titlebar-background-focused", c.bg_deep },
    { "--titlebar-text-color", c.fg_dim },
    { "--titlebar-text-color-focused", c.fg },
    { "--status-bar-background", c.bg_deep },
    { "--status-bar-border-color", c.bg3 },
    { "--status-bar-text-color", c.fg_dim },
    { "--prompt-border-color", c.bg3 },

    -- tables
    { "--table-border-color", c.bg3 },
    { "--table-header-background", c.bg1 },
    { "--table-header-background-hover", c.bg2 },
    { "--table-row-alt-background", c.bg1 },

    -- tags
    { "--tag-color-hover", c.brass },
    { "--tag-background-hover", c.bg2 },
    { "--tag-border-color", c.bg3 },
    { "--tag-border-color-hover", c.frost },

    -- scrollbars
    { "--scrollbar-bg", c.bg0 },
    { "--scrollbar-thumb-bg", c.bg3 },
    { "--scrollbar-active-thumb-bg", c.bg4 },

    -- toggles and sliders
    { "--toggle-thumb-color", c.fg },
    { "--slider-thumb-border-color", c.bg4 },
    { "--interactive-before", c.bg2 },

    -- graph
    { "--graph-node-unresolved", c.error },
    { "--graph-node-focused", c.brass },
    { "--graph-node-attachment", c.sap },
  }

  local rows = {}
  for _, v in ipairs(vars) do
    rows[#rows + 1] = ("  %s: %s;"):format(v[1], v[2])
  end

  -- Every capture takes the colour its Neovim counterpart takes, so a code block
  -- in a note reads the same way as the file it was copied from.
  local cm = {
    { "keyword", c.cinder },
    { "builtin", c.cinder },
    { "meta", c.cinder },
    { "tag", c.cinder },
    { "def", c.brass },
    { "callee", c.brass },
    { "type", c.frost },
    { "variable-3", c.frost },
    { "string", c.sap },
    { "string-2", c.sap },
    { "number", c.sap },
    { "atom", c.sap },
    { "property", c.ember },
    { "qualifier", c.ember },
    { "attribute", c.ember },
    { "variable", c.fg },
    { "variable-2", c.fg },
    { "operator", c.fg_dim },
    { "punctuation", c.fg_dim },
    { "comment", c.comment },
  }

  local edit = {}
  for _, entry in ipairs(cm) do
    edit[#edit + 1] = (".theme-dark .cm-s-obsidian .cm-%s,\n.theme-dark .cm-%s {\n  color: %s !important;\n}")
      :format(entry[1], entry[1], entry[2])
  end

  return ([[
/* cendre for Obsidian · %s
   %s
   generated by scripts/extras.lua, do not edit

   Install: copy this folder to <vault>/.obsidian/themes/cendre, then pick
   cendre under Appearance. Dark only, like the colorscheme.

   Sizes, weights and thicknesses are left alone on purpose: this is a
   colorscheme, so it sets colour and nothing else. */

.theme-dark {
  --accent-h: %d;
  --accent-s: %d%%;
  --accent-l: %d%%;
  --interactive-accent-hsl: var(--accent-h), var(--accent-s), var(--accent-l);
  --background-modifier-error-rgb: %s;

%s
}

/* Syntax inside a code block while editing. Obsidian styles these through
   CodeMirror rather than through variables, so they have to be named. */
%s
]]):format(bg, LINK, h, s, l, channels(c.error),
    table.concat(rows, "\n"), table.concat(edit, "\n\n"))
end
--- The Obsidian manifest. Its version reads 0.0.0 here on purpose: Obsidian compares
--- it against the installed copy to offer an update, so it has to follow the releases,
--- and the sync workflow stamps the released number in as it pushes. Reading
--- .release-please-manifest.json here instead would fail the drift check on every
--- release pull request, which bumps that manifest without re-rendering this file.
--- @param bg string
--- @return string
function M.obsidian_manifest(bg)
  return ([[
{
  "name": "%s",
  "version": "0.0.0",
  "minAppVersion": "1.0.0",
  "author": "Aejkatappaja",
  "authorUrl": "%s"
}
]]):format(palette.name(bg), LINK)
end

--- Firefox reads a WebExtension manifest, which is the only shape a theme can
--- take there. Loaded from about:debugging until it is on addons.mozilla.org.
--- @param bg string
--- @return string
function M.firefox(bg)
  local c = palette.get(bg)
  return ([[
{
  "manifest_version": 2,
  "name": "%s",
  "version": "1.0.0",
  "description": "One wood fire, taken apart. %s",
  "theme": {
    "colors": {
      "frame": "%s",
      "frame_inactive": "%s",
      "tab_background_text": "%s",
      "tab_selected": "%s",
      "tab_text": "%s",
      "tab_line": "%s",
      "tab_loading": "%s",
      "toolbar": "%s",
      "toolbar_text": "%s",
      "toolbar_field": "%s",
      "toolbar_field_text": "%s",
      "toolbar_field_border": "%s",
      "toolbar_field_focus": "%s",
      "toolbar_field_highlight": "%s",
      "toolbar_top_separator": "%s",
      "toolbar_bottom_separator": "%s",
      "toolbar_vertical_separator": "%s",
      "popup": "%s",
      "popup_text": "%s",
      "popup_border": "%s",
      "popup_highlight": "%s",
      "popup_highlight_text": "%s",
      "ntp_background": "%s",
      "ntp_text": "%s",
      "sidebar": "%s",
      "sidebar_text": "%s",
      "sidebar_border": "%s",
      "sidebar_highlight": "%s",
      "sidebar_highlight_text": "%s",
      "bookmark_text": "%s",
      "button_background_hover": "%s",
      "button_background_active": "%s",
      "icons": "%s",
      "icons_attention": "%s"
    },
    "properties": {
      "color_scheme": "dark",
      "content_color_scheme": "dark"
    }
  }
}
]]):format(palette.name(bg), LINK,
    c.bg_deep, c.bg_deep, c.comment, c.bg0, c.fg, c.ember, c.ember,
    c.bg0, c.fg, c.bg1, c.fg, c.bg3, c.bg1, c.vis,
    c.bg3, c.bg3, c.bg3,
    c.bg_deep, c.fg, c.bg3, c.ember, c.bg0,
    c.bg0, c.fg,
    c.bg_deep, c.fg_dim, c.bg3, c.ember, c.bg0,
    c.fg_dim, c.bg1, c.bg2, c.fg_dim, c.ember)
end

--- bat reads a Sublime Text tmTheme, which is an XML property list. Scopes are
--- grouped the way the Neovim treesitter map groups them.
--- @param bg string
--- @return string
function M.bat(bg)
  local c = palette.get(bg)

  --- @param name string
  --- @param scope string|nil
  --- @param fg string|nil
  --- @param bgc string|nil
  --- @param style string|nil
  --- @return string
  local function rule(name, scope, fg, bgc, style)
    local settings = {}
    if fg then table.insert(settings, ("\t\t\t\t<key>foreground</key>\n\t\t\t\t<string>%s</string>"):format(fg)) end
    if bgc then table.insert(settings, ("\t\t\t\t<key>background</key>\n\t\t\t\t<string>%s</string>"):format(bgc)) end
    if style then table.insert(settings, ("\t\t\t\t<key>fontStyle</key>\n\t\t\t\t<string>%s</string>"):format(style)) end
    local head = ("\t\t<dict>\n\t\t\t<key>name</key>\n\t\t\t<string>%s</string>\n"):format(name)
    if scope then
      head = head .. ("\t\t\t<key>scope</key>\n\t\t\t<string>%s</string>\n"):format(scope)
    end
    return head .. "\t\t\t<key>settings</key>\n\t\t\t<dict>\n"
      .. table.concat(settings, "\n") .. "\n\t\t\t</dict>\n\t\t</dict>"
  end

  local global = ("\t\t<dict>\n\t\t\t<key>settings</key>\n\t\t\t<dict>\n"
    .. "\t\t\t\t<key>background</key>\n\t\t\t\t<string>%s</string>\n"
    .. "\t\t\t\t<key>foreground</key>\n\t\t\t\t<string>%s</string>\n"
    .. "\t\t\t\t<key>caret</key>\n\t\t\t\t<string>%s</string>\n"
    .. "\t\t\t\t<key>lineHighlight</key>\n\t\t\t\t<string>%s</string>\n"
    .. "\t\t\t\t<key>selection</key>\n\t\t\t\t<string>%s</string>\n"
    .. "\t\t\t\t<key>gutterForeground</key>\n\t\t\t\t<string>%s</string>\n"
    .. "\t\t\t\t<key>invisibles</key>\n\t\t\t\t<string>%s</string>\n"
    .. "\t\t\t</dict>\n\t\t</dict>"):format(c.bg0, c.fg, c.ember, c.bg1, c.vis, c.gutter, c.bg3)

  local rules = {
    global,
    rule("Comment", "comment, punctuation.definition.comment", c.comment, nil, "italic"),
    rule("String", "string, string.quoted", c.sap),
    rule("String escape", "constant.character.escape", c.ember),
    rule("Regex", "string.regexp", c.ember),
    rule("Number", "constant.numeric", c.sap),
    rule("Boolean and null", "constant.language", c.sap),
    rule("Constant", "constant.other, variable.other.constant", c.fg),
    rule("Keyword", "keyword, storage.type, storage.modifier", c.cinder),
    rule("Operator", "keyword.operator, punctuation.separator, punctuation.terminator", c.fg_dim),
    rule("Punctuation", "punctuation.section, meta.brace", c.fg_dim),
    rule("Function", "entity.name.function, support.function, meta.function-call", c.brass),
    rule("Macro", "entity.name.macro, meta.preprocessor", c.ember),
    rule("Type", "entity.name.type, entity.name.class, support.type, support.class", c.frost),
    rule("Namespace", "entity.name.namespace, entity.name.module", c.frost),
    rule("Variable", "variable, variable.other", c.fg),
    rule("Parameter", "variable.parameter", c.ember),
    rule("Property", "variable.other.member, meta.object-literal.key, support.type.property-name", c.ember),
    rule("Builtin variable", "variable.language", c.cinder),
    rule("Tag", "entity.name.tag", c.cinder),
    rule("Tag attribute", "entity.other.attribute-name", c.ember),
    rule("Decorator", "meta.decorator, punctuation.definition.decorator", c.ember),
    rule("Heading", "markup.heading", c.ember, nil, "bold"),
    rule("Markup bold", "markup.bold", c.brass, nil, "bold"),
    rule("Markup italic", "markup.italic", c.fg, nil, "italic"),
    rule("Markup link", "markup.underline.link", c.frost, nil, "underline"),
    rule("Markup raw", "markup.raw, markup.inline.raw", c.sap),
    rule("Markup quote", "markup.quote", c.comment, nil, "italic"),
    rule("Markup list", "markup.list punctuation.definition", c.ember),
    rule("Diff added", "markup.inserted", c.ok),
    rule("Diff removed", "markup.deleted", c.error),
    rule("Diff changed", "markup.changed", c.info),
    rule("Invalid", "invalid, invalid.illegal", c.error),
    rule("Deprecated", "invalid.deprecated", c.warn),
  }

  return ([[
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>%s</string>
	<key>semanticClass</key>
	<string>theme.dark.%s</string>
	<key>uuid</key>
	<string>%s</string>
	<key>colorSpaceName</key>
	<string>sRGB</string>
	<key>author</key>
	<string>Aejkatappaja</string>
	<key>settings</key>
	<array>
%s
	</array>
</dict>
</plist>
]]):format(palette.name(bg), palette.name(bg),
    ("3f7a1c6e-4b21-4d8f-9c3a-%s"):format(bg == palette.default and "cendre000001"
      or (bg == "medium" and "cendre000002" or "cendre000003")),
    table.concat(rules, "\n"))
end

return M
