# cendre · hard · https://github.com/Aejkatappaja/cendre
# generated by scripts/extras.lua, do not edit
#
# The plugin reads its colours from a case statement in its own src/themes.sh, so
# paste this block there, before its default case, then in tmux.conf:
#   set -g @tokyo-night-tmux_theme "cendre"
#   set -g @tokyo-night-tmux_transparent 0
#
# The transparent option is not cosmetic here: at 1 the plugin overwrites
# "background" below with tmux's "default", and the bar drops onto the terminal's
# own colour instead of the ground this theme picked for it.
#
# The keys are named after ANSI slots, but the plugin only ever paints its own
# statusbar with them, never program output. Four are filled by role instead of by
# name: "blue" is the accent, "bblack" is a block background, "black" is read as a
# foreground, and "white" is the bright ink. Aligning them to their ANSI names
# would look tidier here and worse on screen.
#
# One thing this block cannot fix: the plugin paints the inactive pane border with
# "bblack" too, the slot that fills the active window block. If that border reads
# too loud, put this in tmux.conf after the plugin runs:
#   set -g pane-border-style "fg=#362f2c"

"cendre")
  declare -A THEME=(
    ["background"]="#2a2422"
    ["foreground"]="#e6d5c2"
    ["black"]="#4e4641"
    ["blue"]="#ea9875"
    ["cyan"]="#4e89a2"
    ["green"]="#99af6b"
    ["magenta"]="#9480ba"
    ["red"]="#d1766e"
    ["white"]="#e6d5c2"
    ["yellow"]="#fcba81"

    ["bblack"]="#463e3a"
    ["bblue"]="#8bcfff"
    ["bcyan"]="#20c9cb"
    ["bgreen"]="#43b16a"
    ["bmagenta"]="#a692cd"
    ["bred"]="#d25780"
    ["bwhite"]="#a09384"
    ["byellow"]="#f4a21c"
  )
  ;;
